(library
 (name march_tir)
 (modules tir pp lower mono defun borrow perceus repr escape llvm_emit js_emit purity fold simplify inline dce cprop opt fusion known_call policy_dce beta_adt join_points hot_reload)
 (libraries march_ast march_typecheck march_modules)
 (foreign_stubs (language c) (names native_triple_stub))
)
