(library
 (name march_tir)
 (modules builtin_name tir_names alloc_contract rc_types tir cap_passing pp trmc lower_types lower_state lower_match lower_decls lower_expr lower_actor lower_tests lower mono defun borrow perceus perceus_core perceus_liveness perceus_elide perceus_fbip perceus_scrut repr drop escape llvm_ctx llvm_builtins llvm_eq llvm_data llvm_case llvm_calls llvm_tco llvm_toplevel llvm_repl llvm_emit_simd llvm_emit_nmap llvm_emit_arith llvm_emit_alloc llvm_emit_call llvm_emit_data llvm_emit_html llvm_emit_tcoarm llvm_emit_task llvm_emit js_emit cap_attrib purity fold simplify inline single_use_inline dce cprop opt fusion known_call policy_dce beta_adt join_points hot_reload handler_owner collision_set dispatch_registry clo_flags llvm_dispatch native_map_inline vectorize_check vectorize_mark contract_pipeline)
 (libraries march_ast march_typecheck march_modules march_caps)
 (foreign_stubs (language c) (names native_triple_stub))
)
