(** Known-call optimization.

    After defunctionalization every lambda becomes:
      - A TDClosure struct: TDClosure("$Clo_foo$N", [TPtr TUnit; fv_ty; ...])
      - A lifted apply function: "foo$apply$N($clo, params...)"
      - An allocation at the creation site:
          EAlloc(TCon("$Clo_foo$N", _), [AVar apply_fn; fv_atom; ...])
      - An indirect call at every call site:
          ECallPtr(AVar clo_var, args)

    This pass identifies variables that are provably bound to a specific closure
    allocation, and replaces their ECallPtr dispatch with a direct EApp to the
    known apply function:

        ECallPtr(AVar clo_var, args)
        →  EApp(mk_var apply_fn, [AVar clo_var] ++ args)

    Benefits:
    - Eliminates the indirect function-pointer load through the closure struct.
    - Converts ECallPtr (opaque to purity analysis) to EApp (transparent).
    - When run before Perceus, enables inline.ml to inline the apply function.

    Pipeline position: immediately after Defun, before Perceus.
    Also run inside the Opt fixed-point loop to catch cases revealed by other
    optimizations after Perceus/Escape have run.

    Heuristic: only track allocations in ELet bindings — the common case for
    named closures.  Closures that escape (stored in tuples/records) are
    conservatively left as ECallPtr. *)

(** True for names generated by Defun for closure structs. *)
let is_clo_name s =
  String.length s >= 4 && String.sub s 0 4 = "$Clo"

(** Environment: maps local variable name → apply function name. *)
type clo_env = (string * string) list

let rec go ~changed (env : clo_env) : Tir.expr -> Tir.expr = function

  (* ── Track closure allocations ──────────────────────────────────────── *)
  (* ELet(v, EAlloc("$Clo_...", AVar(apply_fn) :: fv_atoms), body) *)
  | Tir.ELet (v,
      (Tir.EAlloc (Tir.TCon (clo_name, _), (Tir.AVar fn_ptr) :: _) as rhs),
      body)
    when is_clo_name clo_name ->
    let env' = (v.Tir.v_name, fn_ptr.Tir.v_name) :: env in
    Tir.ELet (v, rhs, go ~changed env' body)

  (* Same but for stack-promoted closures (after Escape analysis). *)
  | Tir.ELet (v,
      (Tir.EStackAlloc (Tir.TCon (clo_name, _), (Tir.AVar fn_ptr) :: _) as rhs),
      body)
    when is_clo_name clo_name ->
    let env' = (v.Tir.v_name, fn_ptr.Tir.v_name) :: env in
    Tir.ELet (v, rhs, go ~changed env' body)

  (* ── Convert known ECallPtr to direct EApp ──────────────────────────── *)
  | Tir.ECallPtr (Tir.AVar v, args) ->
    (match List.assoc_opt v.Tir.v_name env with
     | Some apply_name ->
       changed := true;
       (* The apply function takes ($clo, original_params...).
          We pass AVar v as the first argument (the closure pointer itself). *)
       let apply_var = { Tir.v_name = apply_name;
                         v_ty = Tir.TPtr Tir.TUnit;
                         v_lin = Tir.Unr } in
       Tir.EApp (apply_var, Tir.AVar v :: args)
     | None -> Tir.ECallPtr (Tir.AVar v, args))

  (* ── Recursive traversal ────────────────────────────────────────────── *)
  | Tir.ELet (v, rhs, body) ->
    Tir.ELet (v, go ~changed env rhs, go ~changed env body)
  | Tir.ELetRec (fns, body) ->
    Tir.ELetRec (
      List.map (fun fd -> { fd with Tir.fn_body = go ~changed env fd.Tir.fn_body }) fns,
      go ~changed env body)
  | Tir.ECase (a, branches, default) ->
    Tir.ECase (a,
      List.map (fun b -> { b with Tir.br_body = go ~changed env b.Tir.br_body }) branches,
      Option.map (go ~changed env) default)
  | Tir.ESeq (e1, e2) ->
    Tir.ESeq (go ~changed env e1, go ~changed env e2)
  | other -> other

let run ~changed (m : Tir.tir_module) : Tir.tir_module =
  { m with Tir.tm_fns = List.map (fun fd ->
    { fd with Tir.fn_body = go ~changed [] fd.Tir.fn_body }
  ) m.Tir.tm_fns }
