(** Known-call optimization.

    After defunctionalization every lambda becomes:
      - A TDClosure struct: TDClosure("$Clo_foo$N", [TPtr TUnit; fv_ty; ...])
      - A lifted apply function: "foo$apply$N($clo, params...)"
      - An allocation at the creation site:
          EAlloc(TCon("$Clo_foo$N", _), [AVar apply_fn; fv_atom; ...])
      - An indirect call at every call site:
          ECallPtr(AVar clo_var, args)

    This pass identifies variables that are provably bound to a specific closure
    allocation, and replaces their ECallPtr dispatch with a direct EApp to the
    known apply function:

        ECallPtr(AVar clo_var, args)
        →  EApp(mk_var apply_fn, [AVar clo_var] ++ args)

    Benefits:
    - Eliminates the indirect function-pointer load through the closure struct.
    - Converts ECallPtr (opaque to purity analysis) to EApp (transparent).
    - When run before Perceus, enables inline.ml to inline the apply function.

    Pipeline position: immediately after Defun, before Perceus.
    Also run inside the Opt fixed-point loop to catch cases revealed by other
    optimizations after Perceus/Escape have run.

    Heuristic: only track allocations in ELet bindings — the common case for
    named closures.  Closures that escape (stored in tuples/records) are
    conservatively left as ECallPtr. *)

(** True for names generated by Defun for closure structs.

    Converted to [Tir_names.is_clo_struct] (Wave 3 Chunk 2 Task 1): this used
    to be an inline 4-char "$Clo" prefix check, one character short of
    Tir_names's 5-char "$Clo_" (the underscore is part of the producer's
    format string, not incidental). The 4-char check is behaviorally WIDER
    in theory — it would also match a hypothetical "$Clo" name with no
    underscore — but no such name is reachable: the ONLY producer of any
    "$Clo..."-prefixed TCon/TDClosure name in the whole compiler is
    [Tir_names.clo_struct_name] (sprintf pattern: "$Clo_" ^ fn_name ^ "$" ^
    lam_uid), called from exactly defun.ml's two lambda-lifting sites
    (verified by grep: no other "$Clo"-prefixed string literal exists
    anywhere in lib/); fn_name/lam_uid can never make the underscore
    disappear, so every producible name is "$Clo_" + more. The 4-vs-5-char
    widening is therefore unobservable, and switching to the shared
    predicate is a safe, behavior-preserving narrowing. One-way CAS note:
    [lib/cas/serialize.ml]'s [write_type_def] already hashes every
    [TDClosure]'s full name string (including the "$Clo_" prefix) into the
    content-addressed [impl_hash]; [is_clo_name] only READS that
    already-baked-in name to classify it, it never feeds back into hashing,
    so narrowing this predicate cannot retroactively change any existing
    CAS hash. *)
let is_clo_name = Tir_names.is_clo_struct

(** Environment: maps local variable name → apply function name. *)
type clo_env = (string * string) list

(** For an apply function, its own ($clo parameter name, own name) — the pair
    that lets the traversal recognise the SELF-binding defun emits for a local
    recursive fn.  [None] for every other function (only an apply fn has a
    [$clo] parameter, so keying off "parameter 0" anywhere else would resolve
    an ordinary user value to a function). *)
type self_clo = (string * string) option

let rec go ~changed ~(self : self_clo) (env : clo_env) : Tir.expr -> Tir.expr = function

  (* ── Track closure allocations ──────────────────────────────────────── *)
  (* ELet(v, EAlloc("$Clo_...", AVar(apply_fn) :: fv_atoms), body) *)
  | Tir.ELet (v,
      (Tir.EAlloc (Tir.TCon (clo_name, _), (Tir.AVar fn_ptr) :: _) as rhs),
      body)
    when is_clo_name clo_name ->
    let env' = (v.Tir.v_name, fn_ptr.Tir.v_name) :: env in
    Tir.ELet (v, rhs, go ~changed ~self env' body)

  (* Same but for stack-promoted closures (after Escape analysis). *)
  | Tir.ELet (v,
      (Tir.EStackAlloc (Tir.TCon (clo_name, _), (Tir.AVar fn_ptr) :: _) as rhs),
      body)
    when is_clo_name clo_name ->
    let env' = (v.Tir.v_name, fn_ptr.Tir.v_name) :: env in
    Tir.ELet (v, rhs, go ~changed ~self env' body)

  (* ── Track the SELF-binding of a local recursive fn ─────────────────── *)
  (* Defun lifts `fn go(...) ... go(...) ... end` to an apply function whose
     body opens with [let go = $clo] — the lambda's own name rebound to the
     closure it was invoked through — and compiles the recursive call as
     [ECallPtr(AVar go, args)].  That variable is not bound to any [EAlloc]
     in this function, so the two rules above cannot see it; but its apply
     function is known with certainty: it is the one being traversed.

     Resolving it matters for more than the indirect-call hop.  As an
     [ECallPtr] the back-edge is invisible to the self-TCO analysis
     ([Llvm_tco]), which only recognises [EApp]-to-self, so a local recursive
     fn got no back-edge from us at all — it survived deep inputs only
     because LLVM's tail-call elimination turned the emitted self-call into a
     loop, and every Float argument crossing that erased edge was boxed and
     leaked once per iteration ([march-level TCO] in
     specs/progress/2026-08-22-selfrec-closure-float-tail-call.md).  As an
     [EApp] to a known callee it is an ordinary self tail call: TCO gives it
     a real back-edge writing native parameter slots, so no argument is
     boxed and no frame is pushed. *)
  | Tir.ELet (v, (Tir.EAtom (Tir.AVar src) as rhs), body)
    when (match self with
          | Some (clo_param, _) -> String.equal src.Tir.v_name clo_param
          | None -> false) ->
    let apply_name = match self with Some (_, n) -> n | None -> assert false in
    let env' = (v.Tir.v_name, apply_name) :: env in
    Tir.ELet (v, rhs, go ~changed ~self env' body)

  (* ── Convert known ECallPtr to direct EApp ──────────────────────────── *)
  | Tir.ECallPtr (Tir.AVar v, args) ->
    (match List.assoc_opt v.Tir.v_name env with
     | Some apply_name ->
       changed := true;
       (* The apply function takes ($clo, original_params...).
          We pass AVar v as the first argument (the closure pointer itself). *)
       let apply_var = { Tir.v_name = apply_name;
                         v_ty = Tir.TPtr Tir.TUnit;
                         v_lin = Tir.Unr } in
       Tir.EApp (apply_var, Tir.AVar v :: args)
     | None -> Tir.ECallPtr (Tir.AVar v, args))

  (* ── Recursive traversal ────────────────────────────────────────────── *)
  | Tir.ELet (v, rhs, body) ->
    Tir.ELet (v, go ~changed ~self env rhs, go ~changed ~self env body)
  | Tir.ELetRec (fns, body) ->
    Tir.ELetRec (
      List.map (fun fd -> { fd with Tir.fn_body = go ~changed ~self env fd.Tir.fn_body }) fns,
      go ~changed ~self env body)
  | Tir.ECase (a, branches, default) ->
    Tir.ECase (a,
      List.map (fun b -> { b with Tir.br_body = go ~changed ~self env b.Tir.br_body }) branches,
      Option.map (go ~changed ~self env) default)
  | Tir.ESeq (e1, e2) ->
    Tir.ESeq (go ~changed ~self env e1, go ~changed ~self env e2)
  | other -> other

let run ~changed (m : Tir.tir_module) : Tir.tir_module =
  { m with Tir.tm_fns = List.map (fun fd ->
    let self =
      if Tir_names.is_apply_fn fd.Tir.fn_name then
        match fd.Tir.fn_params with
        | clo :: _ -> Some (clo.Tir.v_name, fd.Tir.fn_name)
        | [] -> None
      else None
    in
    { fd with Tir.fn_body = go ~changed ~self [] fd.Tir.fn_body }
  ) m.Tir.tm_fns }
