(* Capability-bearing runtime entry points.

   Generated by joining [builtin_cap_table] (lib/typecheck/typecheck.ml:1661)
   against the march_name -> c_name rows of the codegen builtin table
   (lib/tir/llvm_builtins.ml), then adding the special-lowering cases below by
   hand.  The freshness test in test/test_cap_symbols.ml re-derives the join
   and fails on any drift, so this literal cannot silently rot.

   Special lowerings (no c_name row in llvm_builtins):
   - dns_resolve      -> "dns_resolve" — the C function is UNPREFIXED
                         (runtime/march_runtime.c:3679); the generic fallback
                         emits a call to the bare March name.
   - signal_watch / signal_unwatch / signal_raise_self
                      -> march_signal_* (emitted directly in llvm_emit).
   - task_spawn, task_spawn_steal
                      -> march_task_spawn_thunk (both spawn forms funnel
                         through the same trampoline; cap identity is
                         preserved because both are IO.Spawn).
   - task_spawn_with_cancel
                      -> march_task_spawn_with_cancel_thunk. *)

let table : (string * string) list = [
  (* IO.Console *)
  ("march_println",                "IO.Console");
  ("march_print",                  "IO.Console");
  (* IO.FileRead *)
  ("march_file_exists",            "IO.FileRead");
  ("march_file_read",              "IO.FileRead");
  ("march_file_open",              "IO.FileRead");
  ("march_file_read_line",         "IO.FileRead");
  ("march_file_read_chunk",        "IO.FileRead");
  ("march_file_stat",              "IO.FileRead");
  ("march_dir_exists",             "IO.FileRead");
  ("march_dir_list",               "IO.FileRead");
  ("march_csv_open",               "IO.FileRead");
  ("march_csv_next_row",           "IO.FileRead");
  (* IO.FileWrite *)
  ("march_file_write",             "IO.FileWrite");
  ("march_file_append",            "IO.FileWrite");
  ("march_file_delete",            "IO.FileWrite");
  ("march_file_rename",            "IO.FileWrite");
  ("march_dir_mkdir",              "IO.FileWrite");
  ("march_dir_mkdir_p",            "IO.FileWrite");
  ("march_dir_rmdir",              "IO.FileWrite");
  ("march_dir_rm_rf",              "IO.FileWrite");
  (* IO.FileSystem — needs both read+write *)
  ("march_file_copy",              "IO.FileSystem");
  (* IO.NetConnect *)
  ("march_tcp_connect",            "IO.NetConnect");
  ("march_tcp_send_all",           "IO.NetConnect");
  ("march_tcp_recv_all",           "IO.NetConnect");
  ("march_tcp_recv_exact",         "IO.NetConnect");
  ("march_tcp_recv_http",          "IO.NetConnect");
  ("march_tcp_recv_http_headers",  "IO.NetConnect");
  ("march_tcp_recv_chunk",         "IO.NetConnect");
  ("march_tcp_recv_chunked_frame", "IO.NetConnect");
  (* IO.WebSocket *)
  ("march_ws_recv",                "IO.WebSocket");
  ("march_ws_send",                "IO.WebSocket");
  ("march_ws_select",              "IO.WebSocket");
  (* IO.Network *)
  ("dns_resolve",                  "IO.Network");
  (* IO.NetListen *)
  ("march_tcp_listen",             "IO.NetListen");
  ("march_tcp_accept",             "IO.NetListen");
  ("march_tcp_local_port",         "IO.NetListen");
  ("march_http_server_listen",     "IO.NetListen");
  ("march_http_server_spawn_n",    "IO.NetListen");
  ("march_http_server_wait",       "IO.NetListen");
  (* IO.Process *)
  ("march_process_env",            "IO.Process");
  ("march_process_set_env",        "IO.Process");
  ("march_process_cwd",            "IO.Process");
  ("march_process_argv",           "IO.Process");
  ("march_process_pid",            "IO.Process");
  ("march_process_exit",           "IO.Process");
  ("march_process_spawn_sync",     "IO.Process");
  ("march_process_spawn_lines",    "IO.Process");
  ("march_process_spawn_async",    "IO.Process");
  ("march_process_read_line",      "IO.Process");
  ("march_process_write",          "IO.Process");
  ("march_process_kill_proc",      "IO.Process");
  ("march_process_wait_proc",      "IO.Process");
  (* IO.Clock *)
  ("march_unix_time",              "IO.Clock");
  (* IO.Random *)
  ("march_random_bytes",           "IO.Random");
  ("march_uuid_v4",                "IO.Random");
  (* IO.Signal — special lowering, emitted directly *)
  ("march_signal_watch",           "IO.Signal");
  ("march_signal_unwatch",         "IO.Signal");
  ("march_signal_raise_self",      "IO.Signal");
  (* IO.Spawn — trampoline lowering *)
  ("march_task_spawn_thunk",       "IO.Spawn");
  ("march_task_spawn_with_cancel_thunk", "IO.Spawn");
  (* Vault is IN MEMORY: nothing a read does escapes the process, so a lookup
     carries no ambient authority and needs no capability. What IS authority is
     (a) turning a NAME into a table handle — vault_new/vault_whereis, the
     File.open(path) shape — and (b) mutating state other actors observe.
     Those keep IO.Mut.

     Known trade-off, accepted deliberately: a read of shared mutable state is
     non-deterministic (it observes another actor's writes), so `needs` no
     longer signals "this function is not pure" for readers. Authority remains
     auditable at the boundary — some module named the table and declared the
     capability, and the handle flows through explicit signatures. *)
  (* IO.Mut — shared mutable state via Vault *)
  ("march_vault_new",              "IO.Mut");
  ("march_vault_set",              "IO.Mut");
  ("march_vault_set_ttl",          "IO.Mut");
  ("march_vault_drop",             "IO.Mut");
  ("march_vault_update",           "IO.Mut");
  ("march_vault_put_new",          "IO.Mut");
  ("march_vault_incr",             "IO.Mut");
  ("march_vault_push_capped",      "IO.Mut");
  ("march_vault_ns_set",           "IO.Mut");
  ("march_vault_ns_get",           "IO.Mut");
  ("march_vault_ns_drop",          "IO.Mut");
  ("march_vault_whereis",          "IO.Mut");
  (* IO.NetConnect.TLS *)
  ("march_tls_client_ctx",         "IO.NetConnect.TLS");
  ("march_tls_server_ctx",         "IO.NetConnect.TLS");
  ("march_tls_connect",            "IO.NetConnect.TLS");
  ("march_tls_accept",             "IO.NetConnect.TLS");
  ("march_tls_read",               "IO.NetConnect.TLS");
  ("march_tls_write",              "IO.NetConnect.TLS");
  ("march_tls_negotiated_alpn",    "IO.NetConnect.TLS");
  ("march_tls_peer_cn",            "IO.NetConnect.TLS");
]

(* March-name builtins from builtin_cap_table with NO compiled lowering.
   Each entry needs a justification; the freshness test fails on any
   cap-table builtin that is neither joinable into [table] nor listed here.
   - task_spawn_link: no llvm lowering exists (interpreter/actor-runtime
     path only; nothing to observe in a native binary).
   - get_work_pool:   lowers to a pool-handle global access
     (llvm_emit.ml:369), not a call — no symbol is referenced.
   - unix_time_ms, uuid_v7: interpreter-only builtins today; no compiled
     lowering emits a symbol for them. *)
let uncompiled_builtins : string list =
  [ "task_spawn_link"; "get_work_pool"; "unix_time_ms"; "uuid_v7" ]

let strip_underscore s =
  if String.length s > 0 && s.[0] = '_'
  then String.sub s 1 (String.length s - 1)
  else s

let cap_of_symbol sym = List.assoc_opt (strip_underscore sym) table

let all_caps =
  List.sort_uniq String.compare (List.map snd table)
