/* march_reload.c — HCR Phase 3/4/7 reload server (Linux + macOS, Unix-domain socket).
 *
 * Protocol (newline-terminated text):
 *   PING                                          → PONG
 *   ABI_QUERY                                     → SLOT <id> <name> <impl_hash> <sig_hash> …, END
 *   VERSIONS                                      → VERSION <name> baseline <h> [hot <h>] …, END
 *   VERSIONS_DETAIL                               → SLOT <id> <name> <impl_hash> <activated_at_ms> <signer_hex> …, END
 *   CAS_CHECK <compilation_hash>                  → PRESENT | MISSING
 *   CAS_PUT <compilation_hash> <size_bytes>\n     → READY\n
 *     <binary data, exactly size_bytes>           → OK <hash> | ERR <reason>
 *   ACTIVATE  <name> <impl_hash> <cas_hash> <sig64>  → OK <impl_hash> | ERR <reason>  (v1, legacy)
 *   ACTIVATE2 <name> <impl_hash> <cas_hash> <sig64> <migrate> epoch:<N> callers:<sorted-csv>
 *                                                   → OK <impl_hash> | ERR <reason>  (v2, signed epoch+callers)
 *
 * Artifact CAS layout (server side):
 *   ~/.march/cas/artifacts/<2>/<62>
 *   where <2> = first 2 chars of compilation_hash, <62> = remaining 62 chars.
 *
 * Audit log: every ACTIVATE appends a JSON line to $MARCH_AUDIT_LOG
 *   (default: ${XDG_DATA_HOME:-$HOME/.local/share}/march/audit.jsonl).
 */
#if defined(__linux__) || defined(__APPLE__)

#include "march_reload.h"
#include "march_dispatch.h"
#include "march_runtime.h"
#include "tweetnacl.h"
#include <stdatomic.h>
#include <pthread.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <errno.h>
#include <sys/time.h>

/* ── Signing public key (embedded at build time) ──────────────────────── */
/* Generated by the compiler when --signing-pubkey is passed.
 * All-zeros → signing not configured → ACTIVATE always rejects. */
#ifdef MARCH_SIGNING_PUBKEY_HEX
static unsigned char g_pubkey[32];
static int           g_pubkey_loaded = 0;

static int hex_nibble(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static void load_pubkey_from_hex(void) {
    const char *hex = MARCH_SIGNING_PUBKEY_HEX;
    int ok = (strlen(hex) == 64);
    for (int i = 0; i < 32 && ok; i++) {
        int hi = hex_nibble(hex[2*i]);
        int lo = hex_nibble(hex[2*i+1]);
        if (hi < 0 || lo < 0) { ok = 0; break; }
        g_pubkey[i] = (unsigned char)((hi << 4) | lo);
    }
    g_pubkey_loaded = ok;
}
#define HAVE_SIGNING_KEY 1
#else
static const unsigned char g_pubkey[32] = {0};
static const int           g_pubkey_loaded = 0;
#define HAVE_SIGNING_KEY 0
#endif

/* ── Base64 decode (URL-safe, no-padding) ─────────────────────────────── */

static int b64_val(unsigned char c) {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+' || c == '-') return 62;
    if (c == '/' || c == '_') return 63;
    if (c == '=')             return 0;
    return -1;
}

/* Decode URL-safe base64 (no padding) → raw bytes.
 * Returns decoded length, or -1 on invalid input.
 * out must hold at least ceil(inlen * 3 / 4) bytes. */
static int b64_decode(const char *in, size_t inlen, unsigned char *out) {
    int olen = 0;
    size_t i = 0;
    while (i < inlen) {
        unsigned char c0 = (i < inlen) ? (unsigned char)in[i++] : '=';
        unsigned char c1 = (i < inlen) ? (unsigned char)in[i++] : '=';
        unsigned char c2 = (i < inlen) ? (unsigned char)in[i++] : '=';
        unsigned char c3 = (i < inlen) ? (unsigned char)in[i++] : '=';
        int v0 = b64_val(c0), v1 = b64_val(c1), v2 = b64_val(c2), v3 = b64_val(c3);
        if (v0 < 0 || v1 < 0 || v2 < 0 || v3 < 0) return -1;
        out[olen++] = (unsigned char)((v0 << 2) | (v1 >> 4));
        if (c2 != '=') out[olen++] = (unsigned char)(((v1 & 0xf) << 4) | (v2 >> 2));
        if (c3 != '=') out[olen++] = (unsigned char)(((v2 & 0x3) << 6) | v3);
    }
    return olen;
}

#define RELOAD_BACKLOG  4
#define RELOAD_LINE_MAX 4096
#define CAS_HASH_LEN    64      /* compilation_hash: 64 hex chars */
#define CAS_MAX_ARTIFACT (64 * 1024 * 1024)  /* 64 MB sanity limit */

static char g_socket_path[256];
static char g_cas_root[512];    /* ~/.march/cas */

/* Phase 9: monotonic deploy epoch counter, persisted across server restarts. */
static _Atomic(uint32_t) g_next_epoch;  /* initialised in reload_server_thread */

static void persist_next_epoch(uint32_t next) {
    char path[640], tmp[660];
    snprintf(path, sizeof(path), "%s/next_epoch", g_cas_root);
    snprintf(tmp,  sizeof(tmp),  "%s.tmp",        path);
    FILE *f = fopen(tmp, "w");
    if (!f) return;
    fprintf(f, "%u\n", next);
    fclose(f);
    rename(tmp, path);  /* atomic on POSIX */
}

static uint32_t load_next_epoch(void) {
    char path[640];
    snprintf(path, sizeof(path), "%s/next_epoch", g_cas_root);
    FILE *f = fopen(path, "r");
    if (!f) return 1;  /* first run: start at epoch 1 */
    uint32_t v = 1;
    fscanf(f, "%u", &v);
    fclose(f);
    return v > 0 ? v : 1;
}

/* ── CAS path helpers ────────────────────────────────────────────────── */

/* Validate that s is exactly 64 lowercase-hex characters (CAS hash format). */
static int is_hex64(const char *s) {
    if (!s || s[CAS_HASH_LEN] != '\0') return 0;
    for (int i = 0; i < CAS_HASH_LEN; i++) {
        char c = s[i];
        if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')))
            return 0;
    }
    return 1;
}

static void cas_artifact_path(char *out, size_t outsz, const char *hash) {
    snprintf(out, outsz, "%s/artifacts/%.2s/%.62s", g_cas_root, hash, hash + 2);
}

static void mkdir_p(const char *path) {
    char tmp[512]; snprintf(tmp, sizeof(tmp), "%s", path);
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') { *p = '\0'; mkdir(tmp, 0755); *p = '/'; }
    }
    mkdir(tmp, 0755);
}

/* Read a newline-terminated line into buf (NUL-terminated, newline stripped).
 * Returns bytes read (>=0), -1 on EOF/error, or -(max-1) if the line was
 * truncated (too long).  On truncation the stream is drained to the next '\n'
 * so subsequent commands are not desynced. */
static int read_line(int fd, char *buf, int max) {
    int n = 0;
    while (1) {
        char c;
        int r = (int)read(fd, &c, 1);
        if (r <= 0) return r ? r : -1;
        if (c == '\n') break;
        if (c == '\r') continue;
        if (n < max - 1) buf[n++] = c;
        /* else: buffer full — keep draining until '\n' to avoid desync */
    }
    buf[n] = '\0';
    return (n < max - 1) ? n : -(max - 1);
}

/* Read exactly nbytes from fd into buf. Returns 0 on success, -1 on error/EOF. */
static int read_exact(int fd, unsigned char *buf, size_t nbytes) {
    size_t got = 0;
    while (got < nbytes) {
        ssize_t r = read(fd, buf + got, nbytes - got);
        if (r <= 0) return -1;
        got += (size_t)r;
    }
    return 0;
}

static void wresp(int fd, const char *s) { write(fd, s, strlen(s)); }

/* Write the result of snprintf safely: clamp to bufsz-1 to guard against
 * the snprintf+write overread (snprintf returns would-have-written, not
 * actually-written; writing that many bytes reads off the end of the buffer
 * when the format string's inputs exceed bufsz). */
static void write_safe(int fd, const char *buf, int snprintf_ret, size_t bufsz) {
    int n = snprintf_ret < (int)bufsz ? snprintf_ret : (int)bufsz - 1;
    if (n > 0) write(fd, buf, (size_t)n);
}

/* ── Audit log ───────────────────────────────────────────────────────────── */

static void pubkey_to_hex(char out[65]) {
    out[0] = '\0';
#if HAVE_SIGNING_KEY
    if (!g_pubkey_loaded) return;
    static const char hc[] = "0123456789abcdef";
    for (int i = 0; i < 32; i++) {
        out[2*i]   = hc[(g_pubkey[i] >> 4) & 0xf];
        out[2*i+1] = hc[g_pubkey[i] & 0xf];
    }
    out[64] = '\0';
#endif
}

/* Append one JSON line to the audit log. Path is $MARCH_AUDIT_LOG, or
 * ${XDG_DATA_HOME:-$HOME/.local/share}/march/audit.jsonl by default. */
static void write_audit_log(const char *fn, const char *impl_hash,
                             const char *cas_hash, const char *result) {
    const char *log_path = getenv("MARCH_AUDIT_LOG");
    char default_path[512];
    if (!log_path || !log_path[0]) {
        const char *xdg = getenv("XDG_DATA_HOME");
        if (xdg && xdg[0])
            snprintf(default_path, sizeof(default_path), "%s/march/audit.jsonl", xdg);
        else {
            const char *home = getenv("HOME");
            if (!home || !home[0]) return;
            snprintf(default_path, sizeof(default_path),
                     "%s/.local/share/march/audit.jsonl", home);
        }
        log_path = default_path;
    }
    /* Ensure parent directory exists */
    char dir[512];
    snprintf(dir, sizeof(dir), "%s", log_path);
    char *slash = strrchr(dir, '/');
    if (slash) { *slash = '\0'; mkdir_p(dir); }

    struct timeval tv;
    gettimeofday(&tv, NULL);
    long long ts_ms = (long long)tv.tv_sec * 1000LL + (long long)tv.tv_usec / 1000;

    char signer[65]; pubkey_to_hex(signer);

    FILE *f = fopen(log_path, "a");
    if (!f) return;
    fprintf(f,
        "{\"ts\":%lld,\"type\":\"activate\",\"fn\":\"%s\","
        "\"impl_hash\":\"%s\",\"signer\":\"%s\","
        "\"cas_hash\":\"%s\",\"result\":\"%s\"}\n",
        ts_ms, fn ? fn : "", impl_hash ? impl_hash : "",
        signer, cas_hash ? cas_hash : "", result);
    fclose(f);
}

/* RTLD_DEEPBIND: prefer this .so's own symbols over the main executable's.
 * Without it, a hot-patched function resolves PLT calls to the compiled-in v1
 * instead of the v2 copies in the patch .so.  GNU extension; guard it. */
#ifndef RTLD_DEEPBIND
#define RTLD_DEEPBIND 0
#endif

/* Common activation body shared by ACTIVATE (v1) and ACTIVATE2 (v2).
 * callers_csv: comma-separated caller list (already sorted for v2; raw for v1),
 *              or NULL if absent. */
static void do_activate(int fd, const char *name, const char *impl_hash,
                        const char *cas_hash, int migrate_required,
                        uint32_t activate_epoch, const char *callers_csv) {
    uint32_t slot_id;
    if (!march_dispatch_name_to_id(name, &slot_id)) {
        write_audit_log(name, impl_hash, cas_hash, "err_abi");
        char resp[512];
        int n = snprintf(resp, sizeof(resp), "ERR unknown_name %s\n", name);
        write_safe(fd, resp, n, sizeof(resp));
        return;
    }

    char path[640]; cas_artifact_path(path, sizeof(path), cas_hash);
    if (access(path, F_OK) != 0) {
        write_audit_log(name, impl_hash, cas_hash, "err_cas_miss");
        wresp(fd, "ERR missing_artifact\n"); return;
    }

    void *handle = dlopen(path, RTLD_NOW | RTLD_GLOBAL | RTLD_DEEPBIND);
    if (!handle) {
        write_audit_log(name, impl_hash, cas_hash, "err_dlopen");
        char resp[512];
        int n = snprintf(resp, sizeof(resp), "ERR dlopen_failed %s\n", dlerror());
        write_safe(fd, resp, n, sizeof(resp));
        return;
    }

    void *fn_ptr = dlsym(handle, name);
    if (!fn_ptr) {
        char resp[512];
        int n = snprintf(resp, sizeof(resp), "ERR dlsym_failed %s\n", name);
        dlclose(handle);
        write_safe(fd, resp, n, sizeof(resp));
        return;
    }

    if (activate_epoch > 0) {
        void (*init_fn)(uint32_t) = NULL;
        void *raw_init = dlsym(handle, "__march_init");
        if (raw_init) memcpy(&init_fn, &raw_init, sizeof(init_fn));
        if (init_fn) init_fn(activate_epoch);
    }

    int idx = (activate_epoch > 0)
        ? march_dispatch_publish_epoch(slot_id, fn_ptr, impl_hash, NULL,
                                       (uint8_t)MARCH_NATIVE, activate_epoch)
        : march_dispatch_publish(slot_id, fn_ptr, impl_hash, NULL,
                                (uint8_t)MARCH_NATIVE);
    if (idx < 0) {
        wresp(fd, "ERR publish_failed all_slots_pinned\n");
        dlclose(handle);
        return;
    }
    /* Dispatch table owns the handle from this point; it will dlclose when the
     * ring slot is reclaimed by the next hot deploy. */
    march_dispatch_set_handle(slot_id, (uint32_t)idx, handle);

    {
        struct timeval atv; gettimeofday(&atv, NULL);
        long long ats = (long long)atv.tv_sec * 1000LL + (long long)atv.tv_usec / 1000;
        char asigner[65]; pubkey_to_hex(asigner);
        march_dispatch_set_activation(slot_id, ats, asigner);
    }

    /* Optional actor migration: dlsym __migrate_<Actor> and broadcast. */
    if (migrate_required) {
        char migrate_sym[320];
        const char *dispatch_sfx = "_dispatch";
        size_t name_len = strlen(name);
        size_t dsfx_len = strlen(dispatch_sfx);
        char actor_short[256];
        if (name_len > dsfx_len &&
            strcmp(name + name_len - dsfx_len, dispatch_sfx) == 0) {
            size_t alen = name_len - dsfx_len;
            if (alen >= sizeof(actor_short)) alen = sizeof(actor_short) - 1;
            strncpy(actor_short, name, alen);
            actor_short[alen] = '\0';
        } else {
            strncpy(actor_short, name, sizeof(actor_short) - 1);
            actor_short[sizeof(actor_short) - 1] = '\0';
        }
        snprintf(migrate_sym, sizeof(migrate_sym), "__migrate_%s", actor_short);
        for (char *p = migrate_sym + 10; *p; p++) {
            if (*p == '.') *p = '_';
        }
        void *raw_sym = dlsym(handle, migrate_sym);
        void *(*migrate_fn)(void *) = NULL;
        if (raw_sym) {
            memcpy(&migrate_fn, &raw_sym, sizeof(migrate_fn));
            fprintf(stderr, "[hcr] migrate: found %s, broadcasting to slot %u\n",
                    migrate_sym, slot_id);
        } else {
            /* Symbol absent but migrate_required=1 (e.g. @compat(any) with schema
             * changes and no migrate_state fn).  Log to stderr only — writing WARN
             * before OK would desync the client's response parser. */
            fprintf(stderr, "[hcr] migrate: symbol not found: %s (proceeding without migration)\n",
                    migrate_sym);
        }
        march_actor_broadcast_migrate(slot_id, migrate_fn);
    }

    march_dispatch_set_callers(slot_id, callers_csv && callers_csv[0] ? callers_csv : NULL);
    write_audit_log(name, impl_hash, cas_hash, "ok");
    char resp[256];
    int n = snprintf(resp, sizeof(resp), "OK %s\n", impl_hash);
    write_safe(fd, resp, n, sizeof(resp));
}

static void handle_client(int fd) {
    char line[RELOAD_LINE_MAX];
    while (1) {
        int r = read_line(fd, line, RELOAD_LINE_MAX);
        if (r <= 0) break;

        /* ── PING ─────────────────────────────────────────────────────── */
        if (strcmp(line, "PING") == 0) {
            wresp(fd, "PONG\n");

        /* ── ABI_QUERY ────────────────────────────────────────────────── */
        } else if (strcmp(line, "ABI_QUERY") == 0) {
            for (uint32_t i = 1; i < 65536; i++) {  /* 1-based; slot 0 = sentinel */
                uint32_t cur = march_dispatch_current(i);
                const char *h = march_dispatch_impl_hash(i, cur);
                if (!h) break;
                const char *name    = march_dispatch_id_to_name(i);
                const char *sig     = march_dispatch_sig_hash(i, cur);
                const char *callers = march_dispatch_callers(i);
                char resp[1024];
                int n;
                if (callers && callers[0]) {
                    n = snprintf(resp, sizeof(resp), "SLOT %u %s %s %s callers:%s\n",
                                 i,
                                 name ? name : "(none)",
                                 h[0] ? h : "(none)",
                                 sig && sig[0] ? sig : "(none)",
                                 callers);
                } else {
                    n = snprintf(resp, sizeof(resp), "SLOT %u %s %s %s\n",
                                 i,
                                 name ? name : "(none)",
                                 h[0] ? h : "(none)",
                                 sig && sig[0] ? sig : "(none)");
                }
                write_safe(fd, resp, n, sizeof(resp));
            }
            wresp(fd, "END\n");

        /* ── VERSIONS ─────────────────────────────────────────────────── */
        } else if (strcmp(line, "VERSIONS") == 0) {
            for (uint32_t i = 1; i < 65536; i++) {  /* 1-based; slot 0 = sentinel */
                const char *name = march_dispatch_id_to_name(i);
                if (!name) break;
                const char *base = march_dispatch_baseline_hash(i);
                uint32_t cur = march_dispatch_current(i);
                const char *hot  = march_dispatch_impl_hash(i, cur);
                char resp[512];
                int n = snprintf(resp, sizeof(resp), "VERSION %s baseline %s\n",
                                 name, base && base[0] ? base : "(none)");
                write_safe(fd, resp, n, sizeof(resp));
                /* Emit "hot" line only when impl_hash differs from baseline */
                if (hot && hot[0] && base && base[0] && strcmp(hot, base) != 0) {
                    n = snprintf(resp, sizeof(resp), "VERSION %s hot %s\n", name, hot);
                    write_safe(fd, resp, n, sizeof(resp));
                }
            }
            wresp(fd, "END\n");

        /* ── VERSIONS_DETAIL ──────────────────────────────────────────── */
        } else if (strcmp(line, "VERSIONS_DETAIL") == 0) {
            for (uint32_t i = 1; i < 65536; i++) {  /* 1-based; slot 0 = sentinel */
                const char *name = march_dispatch_id_to_name(i);
                if (!name) break;
                uint32_t cur = march_dispatch_current(i);
                const char *h   = march_dispatch_impl_hash(i, cur);
                long long   ts  = march_dispatch_activated_at(i);
                const char *sig = march_dispatch_signer_hex(i);
                uint32_t    ep  = march_dispatch_epoch(i, cur);
                char resp[512];
                int n = snprintf(resp, sizeof(resp),
                                 "SLOT %u %s %s %lld %s %u\n",
                                 i,
                                 name,
                                 h && h[0] ? h : "(none)",
                                 ts,
                                 sig && sig[0] ? sig : "(none)",
                                 ep);
                write_safe(fd, resp, n, sizeof(resp));
            }
            wresp(fd, "END\n");

        /* ── CAS_CHECK ────────────────────────────────────────────────── */
        } else if (strncmp(line, "CAS_CHECK ", 10) == 0) {
            const char *hash = line + 10;
            if (!is_hex64(hash)) {
                wresp(fd, "ERR bad_hash\n"); continue;
            }
            char path[640]; cas_artifact_path(path, sizeof(path), hash);
            wresp(fd, (access(path, F_OK) == 0) ? "PRESENT\n" : "MISSING\n");

        /* ── CAS_PUT ──────────────────────────────────────────────────── */
        } else if (strncmp(line, "CAS_PUT ", 8) == 0) {
            char hash[65]; long long size_ll;
            if (sscanf(line + 8, "%64s %lld", hash, &size_ll) != 2
                || !is_hex64(hash)
                || size_ll <= 0 || size_ll > CAS_MAX_ARTIFACT) {
                wresp(fd, "ERR bad_format\n"); continue;
            }
            size_t sz = (size_t)size_ll;
            unsigned char *buf = (unsigned char *)malloc(sz);
            if (!buf) { wresp(fd, "ERR oom\n"); continue; }
            wresp(fd, "READY\n");
            if (read_exact(fd, buf, sz) != 0) {
                /* Stream is desynced — close rather than trying to recover. */
                free(buf); close(fd); return;
            }
            /* Write to CAS */
            char path[640]; cas_artifact_path(path, sizeof(path), hash);
            /* Ensure parent directory exists */
            char dir[640]; snprintf(dir, sizeof(dir), "%s/artifacts/%.2s", g_cas_root, hash);
            mkdir_p(dir);
            /* Write atomically via tmp file */
            char tmp[660]; snprintf(tmp, sizeof(tmp), "%s.tmp", path);
            FILE *f = fopen(tmp, "wb");
            if (!f) { free(buf); wresp(fd, "ERR open_failed\n"); continue; }
            size_t written = fwrite(buf, 1, sz, f);
            fclose(f); free(buf);
            if (written != sz) { unlink(tmp); wresp(fd, "ERR write_failed\n"); continue; }
            if (rename(tmp, path) != 0) { unlink(tmp); wresp(fd, "ERR rename_failed\n"); continue; }
            char resp[128];
            int n = snprintf(resp, sizeof(resp), "OK %s\n", hash);
            write_safe(fd, resp, n, sizeof(resp));

        /* ── ACTIVATE ─────────────────────────────────────────────────── */
        } else if (strncmp(line, "ACTIVATE ", 9) == 0) {
            char name[256], impl_hash[128], cas_hash[128], sig_b64[256];
            char migrate_required_str[8] = {0};
            int parsed = sscanf(line + 9, "%255s %127s %127s %255s %7s",
                                name, impl_hash, cas_hash, sig_b64,
                                migrate_required_str);
            if (parsed < 4) {
                wresp(fd, "ERR bad_format\n"); continue;
            }
            if (!is_hex64(cas_hash)) {
                wresp(fd, "ERR bad_cas_hash\n"); continue;
            }
            int migrate_required = (parsed >= 5 && migrate_required_str[0] == '1') ? 1 : 0;

#if HAVE_SIGNING_KEY
            /* Verify ed25519 signature before doing anything else. */
            if (!g_pubkey_loaded) {
                wresp(fd, "ERR signing_not_configured\n"); continue;
            }
            /* Check for all-zero pubkey (signing not configured) */
            int all_zero = 1;
            for (int i = 0; i < 32; i++) if (g_pubkey[i]) { all_zero = 0; break; }
            if (all_zero) { wresp(fd, "ERR signing_not_configured\n"); continue; }

            /* Signed message is "<name> <impl_hash> <cas_hash>" */
            char signed_msg[640];
            int smlen = snprintf(signed_msg, sizeof(signed_msg), "%s %s %s",
                                 name, impl_hash, cas_hash);

            /* Decode base64 signature */
            unsigned char sigbytes[64];
            int siglen = b64_decode(sig_b64, strlen(sig_b64), sigbytes);
            if (siglen != 64) { wresp(fd, "ERR bad_signature\n"); continue; }

            /* Build the signed message in tweetnacl format: sig || message */
            unsigned char *sm = (unsigned char *)malloc((size_t)(smlen + 64));
            if (!sm) { wresp(fd, "ERR oom\n"); continue; }
            memcpy(sm, sigbytes, 64);
            memcpy(sm + 64, signed_msg, (size_t)smlen);

            unsigned char *m_out = (unsigned char *)malloc((size_t)(smlen + 64));
            unsigned long long m_out_len = 0;
            int vrc = crypto_sign_open(m_out, &m_out_len, sm, (unsigned long long)(smlen + 64), g_pubkey);
            free(sm); free(m_out);
            if (vrc != 0) {
                write_audit_log(name, impl_hash, cas_hash, "err_sig");
                wresp(fd, "ERR bad_signature\n"); continue;
            }
#else
            (void)sig_b64;
            write_audit_log(name, impl_hash, cas_hash, "err_sig");
            wresp(fd, "ERR signing_not_configured\n"); continue;
#endif
            {
                uint32_t activate_epoch = 0;
                const char *ep_ptr = strstr(line, " epoch:");
                if (ep_ptr) activate_epoch = (uint32_t)atoi(ep_ptr + 7);
                const char *callers_ptr = strstr(line, " callers:");
                do_activate(fd, name, impl_hash, cas_hash, migrate_required,
                            activate_epoch, callers_ptr ? callers_ptr + 9 : NULL);
            }

        /* ── ACTIVATE2 ─────────────────────────────────────────────────── */
        /* Protocol v2: epoch and callers are included in the signed payload,
         * preventing replay attacks that forge the epoch or caller list.
         * Signed message: "ACTIVATE2 <name> <impl_hash> <cas_hash> epoch:<N> callers:<sorted-csv>" */
        } else if (strncmp(line, "ACTIVATE2 ", 10) == 0) {
            char name[256], impl_hash[128], cas_hash[128], sig_b64[256];
            char migrate_str[8] = {0};
            if (sscanf(line + 10, "%255s %127s %127s %255s %7s",
                       name, impl_hash, cas_hash, sig_b64, migrate_str) < 5) {
                wresp(fd, "ERR bad_format\n"); continue;
            }
            if (!is_hex64(cas_hash)) {
                wresp(fd, "ERR bad_cas_hash\n"); continue;
            }
            int migrate_required = (migrate_str[0] == '1') ? 1 : 0;

            /* Parse mandatory epoch:<N>. */
            uint32_t activate_epoch = 0;
            {
                const char *ep = strstr(line, " epoch:");
                if (!ep) { wresp(fd, "ERR bad_format missing_epoch\n"); continue; }
                activate_epoch = (uint32_t)atoi(ep + 7);
            }

            /* Parse mandatory callers:<csv>, then sort for canonical form. */
            char callers_sorted[1024] = {0};
            {
                const char *cp = strstr(line, " callers:");
                if (!cp) { wresp(fd, "ERR bad_format missing_callers\n"); continue; }
                const char *csv = cp + 9;
                char tmp[1024]; size_t tlen = 0;
                while (csv[tlen] && csv[tlen] != '\n' && csv[tlen] != '\r'
                       && tlen < sizeof(tmp) - 1)
                    tlen++;
                memcpy(tmp, csv, tlen); tmp[tlen] = '\0';

                if (tmp[0] != '\0') {
                    char *tokens[256]; int ntok = 0;
                    char *p = tmp;
                    while (*p && ntok < 255) {
                        tokens[ntok++] = p;
                        char *c = strchr(p, ',');
                        if (!c) break;
                        *c = '\0'; p = c + 1;
                    }
                    for (int i = 1; i < ntok; i++) {
                        char *key = tokens[i]; int j = i - 1;
                        while (j >= 0 && strcmp(tokens[j], key) > 0)
                            { tokens[j+1] = tokens[j]; j--; }
                        tokens[j+1] = key;
                    }
                    char *out = callers_sorted; size_t rem = sizeof(callers_sorted);
                    for (int i = 0; i < ntok && rem > 1; i++) {
                        if (i > 0) { *out++ = ','; rem--; }
                        size_t sl = strlen(tokens[i]);
                        if (sl >= rem) sl = rem - 1;
                        memcpy(out, tokens[i], sl); out += sl; rem -= sl;
                    }
                    *out = '\0';
                }
            }

#if HAVE_SIGNING_KEY
            if (!g_pubkey_loaded) {
                wresp(fd, "ERR signing_not_configured\n"); continue;
            }
            int all_zero = 1;
            for (int i = 0; i < 32; i++) if (g_pubkey[i]) { all_zero = 0; break; }
            if (all_zero) { wresp(fd, "ERR signing_not_configured\n"); continue; }

            /* Reconstruct the canonical signed message from parsed values. */
            char signed_msg[1024];
            int smlen = snprintf(signed_msg, sizeof(signed_msg),
                                 "ACTIVATE2 %s %s %s epoch:%u callers:%s",
                                 name, impl_hash, cas_hash, activate_epoch, callers_sorted);

            unsigned char sigbytes[64];
            int siglen = b64_decode(sig_b64, strlen(sig_b64), sigbytes);
            if (siglen != 64) { wresp(fd, "ERR bad_signature\n"); continue; }

            unsigned char *sm = (unsigned char *)malloc((size_t)(smlen + 64));
            if (!sm) { wresp(fd, "ERR oom\n"); continue; }
            memcpy(sm, sigbytes, 64);
            memcpy(sm + 64, signed_msg, (size_t)smlen);
            unsigned char *m_out = (unsigned char *)malloc((size_t)(smlen + 64));
            unsigned long long m_out_len = 0;
            int vrc = crypto_sign_open(m_out, &m_out_len, sm,
                                       (unsigned long long)(smlen + 64), g_pubkey);
            free(sm); free(m_out);
            if (vrc != 0) {
                write_audit_log(name, impl_hash, cas_hash, "err_sig");
                wresp(fd, "ERR bad_signature\n"); continue;
            }
#else
            (void)sig_b64;
            write_audit_log(name, impl_hash, cas_hash, "err_sig");
            wresp(fd, "ERR signing_not_configured\n"); continue;
#endif
            do_activate(fd, name, impl_hash, cas_hash, migrate_required,
                        activate_epoch, callers_sorted);

        /* ── GET_EPOCH ────────────────────────────────────────────────── */
        } else if (strcmp(line, "GET_EPOCH") == 0) {
            uint32_t e = atomic_fetch_add_explicit(&g_next_epoch, 1,
                                                    memory_order_acq_rel);
            persist_next_epoch(e + 1);
            char resp[64];
            int n = snprintf(resp, sizeof(resp), "EPOCH %u\n", e);
            write_safe(fd, resp, n, sizeof(resp));

        } else {
            wresp(fd, "ERR unknown_command\n");
        }
    }
    close(fd);
}

static void *reload_server_thread(void *arg) {
    (void)arg;

#if HAVE_SIGNING_KEY
    load_pubkey_from_hex();
#endif
    /* Phase 9: restore epoch counter from disk (g_cas_root already set). */
    atomic_store_explicit(&g_next_epoch, load_next_epoch(), memory_order_relaxed);

    int srv = socket(AF_UNIX, SOCK_STREAM, 0);
    if (srv < 0) { perror("march_reload: socket"); return NULL; }

    struct sockaddr_un addr;
    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, g_socket_path, sizeof(addr.sun_path) - 1);

    unlink(g_socket_path);
    if (bind(srv, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("march_reload: bind"); close(srv); return NULL;
    }
    listen(srv, RELOAD_BACKLOG);
    fprintf(stderr, "[hcr] reload server listening on %s\n", g_socket_path);

    while (1) {
        int cli = accept(srv, NULL, NULL);
        if (cli < 0) {
            if (errno == EINTR) continue;
            perror("march_reload: accept");
            break;
        }
        handle_client(cli);
    }
    unlink(g_socket_path);
    close(srv);
    return NULL;
}

void march_reload_server_start(const char *socket_path) {
    if (!socket_path || socket_path[0] == '\0') return;
    strncpy(g_socket_path, socket_path, sizeof(g_socket_path) - 1);
    g_socket_path[sizeof(g_socket_path) - 1] = '\0';

    /* Build CAS root path: ~/.march/cas */
    const char *home = getenv("HOME");
    if (home)
        snprintf(g_cas_root, sizeof(g_cas_root), "%s/.march/cas", home);
    else
        snprintf(g_cas_root, sizeof(g_cas_root), "/tmp/.march_cas");

    pthread_t tid;
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    pthread_create(&tid, &attr, reload_server_thread, NULL);
    pthread_attr_destroy(&attr);
}

#else  /* non-POSIX stub */

#include "march_reload.h"

void march_reload_server_start(const char *socket_path) {
    (void)socket_path;
}

#endif /* __linux__ || __APPLE__ */
