(** [forge host init] (distributed-deploys build step 10b, item 2).

    - [local]: the host script run by this machine's [sh] against a
      scratch directory ([Host_layout] relocated under a prefix, no user
      creation, no chown): the files and the environment the unit gets, the
      shared-secret and certificate modes, and idempotence (a second run
      changes nothing).
    - [container]: the acceptance: the real thing over ssh against a
      Docker container running sshd (alpine), as root: the march user, the
      directories, the files with their owners and modes, the recorded
      target, and a second run that changes nothing. Skipped, loudly, when
      Docker is absent or cannot build the image; never a vacuous pass. *)

open March_forge

let contains s sub =
  let n = String.length s and k = String.length sub in
  let rec go i = i + k <= n && (String.sub s i k = sub || go (i + 1)) in
  go 0

let read_file path = try In_channel.with_open_bin path In_channel.input_all with Sys_error _ -> ""
let write_file path s = Out_channel.with_open_bin path (fun oc -> output_string oc s)
let rec mkdir_p d = if not (Sys.file_exists d) then (mkdir_p (Filename.dirname d); Unix.mkdir d 0o755)

let short_tmp tag =
  let d = Printf.sprintf "/tmp/fhi%s%d_%d" tag (Unix.getpid ()) (Random.int 100000) in
  Unix.mkdir d 0o755; d

let expect what text subs =
  List.iter (fun s -> if not (contains text s) then Alcotest.failf "%s: expected %S in:\n%s" what s text) subs

let refuse what text subs =
  List.iter (fun s -> if contains text s then Alcotest.failf "%s: did not expect %S in:\n%s" what s text) subs

(** A two-pool ssh project under [dir]/proj, its deploy key in [dir]/home.
    [hosts]: the overlay's host of pool a and of pool b. *)
let make_project ~dir ~host_a ~host_b =
  let root = Filename.concat dir "proj" in
  mkdir_p (Filename.concat root "src");
  write_file (Filename.concat root "forge.toml") "[package]\nname = \"app\"\nversion = \"0.1.0\"\n";
  write_file (Filename.concat root "src/app.march")
    "mod App do\n  protocol Echo do\n    ask: Client -> Server : Int\n    answer: Server -> Client : Int\n  end\n\
    \  fn serve(x) do x end\nend\n";
  write_file (Filename.concat root "topology.toml")
    "[roles]\n\"Echo.Server\" = { body = \"App.serve\" }\n\n\
     [pool.a]\nserves = [\"Echo.Server\"]\ncaps = [\"IO.Console\"]\npublic = [8080]\n\n\
     [pool.b]\nserves = [\"Echo.Server\"]\ninitiates = [\"Echo.Client\"]\ncaps = []\n";
  write_file (Filename.concat root "topology.prod.toml")
    (Printf.sprintf "[pool.a]\nhosts = [{ host = %S, labels = [\"edge\"] }]\n\n[pool.b]\nhosts = [%S]\n\n\
                     [backend]\nkind = \"ssh\"\n" host_a host_b);
  let home = Filename.concat dir "home" in
  mkdir_p home;
  Unix.putenv "HOME" home;
  let (_, sk) = March_ed25519.Ed25519.keygen () in
  (match Cmd_hot_reload.save_sk sk with Ok () -> () | Error m -> Alcotest.fail m);
  match Project.load_from_dir root with
  | Ok p -> p
  | Error m -> Alcotest.fail m

let with_home f =
  let old = Sys.getenv_opt "HOME" in
  Fun.protect ~finally:(fun () -> Option.iter (Unix.putenv "HOME") old) f

let opts = Host_init.default_opts (Some "prod")

(* ── local ─────────────────────────────────────────────────────────────── *)

let test_local_idempotent () =
  with_home @@ fun () ->
  let dir = short_tmp "l" in
  let proj = make_project ~dir ~host_a:"root@web-1" ~host_b:"root@web-2" in
  let root = proj.Project.root in
  let prefix = Filename.concat dir "host" in
  mkdir_p prefix;
  let run () = Host_init.run ~transport:Remote.local ~service_ctl:"false" ~layout_prefix:prefix ~proj ~opts () in
  let first = match run () with Ok r -> r | Error m -> Alcotest.failf "first run failed:\n%s" m in
  expect "first run" first [ "2 host(s), shared-secret mode"; "a-web-1 (root@web-1, pool a): "; "changed (";
                             "note: systemd is not running here: march-a.service was written, not enabled" ];
  let layout = Host_layout.make ~prefix "app" in
  let unit_a = read_file (Host_layout.unit_file layout "a") in
  expect "unit a" unit_a
    [ "User=march"; "ExecStart=/opt/march/app/app"; "Environment=MARCH_POOLS=a"; "Environment=MARCH_NODE_NAME=a-web-1";
      "Environment=MARCH_NODE_PORT=7946"; "Environment=MARCH_NODE_ADVERTISE=web-1:7946";
      "Environment=MARCH_CLUSTER_NODES=web-2:7946"; "Environment=MARCH_NODE_LABELS=edge";
      "Environment=MARCH_TOPOLOGY_FILE=/etc/march/app/topology.json";
      "Environment=MARCH_TOPOLOGY_STATUS=/var/lib/march/app/run/a.status";
      "Environment=MARCH_HOT_RELOAD_SOCKET=/var/lib/march/app/run/a.sock";
      "Environment=MARCH_DEPLOY_POLICY=/etc/march/app/a.policy"; "Environment=HOME=/var/lib/march/app";
      "EnvironmentFile=-/etc/march/app/a.env"; "generated by `forge host init`" ];
  refuse "unit a (secrets stay out of the world-readable unit)" unit_a [ "MARCH_CLUSTER_SECRET"; "MARCH_NODE_CERT" ];
  let secret = String.trim (read_file (Filename.concat root ".forge/hosts/prod/cluster.secret")) in
  Alcotest.(check int) "a 32-byte secret" 64 (String.length secret);
  Alcotest.(check string) "env file" ("MARCH_CLUSTER_SECRET=" ^ secret ^ "\n") (read_file (Host_layout.env_file layout "a"));
  Alcotest.(check int) "env file mode" 0o640 ((Unix.stat (Host_layout.env_file layout "a")).Unix.st_perm);
  Alcotest.(check string) "policy a: the written caps" "IO.Console\n" (read_file (Host_layout.policy_file layout "a"));
  Alcotest.(check string) "policy b: caps = [] allows nothing" "" (read_file (Host_layout.policy_file layout "b"));
  expect "firewall a" (read_file (Host_layout.firewall_file layout "a"))
    [ "ufw allow 22/tcp"; "ufw allow 8080/tcp"; "ufw allow from web-2 to any port 7946" ];
  Alcotest.(check bool) "deploy.pub" true (String.length (read_file (Host_layout.deploy_pub layout)) > 40);
  expect "topology" (read_file (Host_layout.topology_file layout)) [ "\"version\": 1"; "\"Echo.Server\"" ];
  expect "do-firewall written locally" (read_file (Filename.concat root ".forge/hosts/prod/do-firewalls.json"))
    [ "march-a"; "8080" ];
  (match Reconcile.read_host_records ~root (Some "prod") with
   | Ok [ a; b ] ->
     Alcotest.(check string) "node" "a-web-1" a.Reconcile.hr_node;
     Alcotest.(check string) "pool" "b" b.Reconcile.hr_pool;
     Alcotest.(check bool) ("target from uname: " ^ a.hr_uname ^ " -> " ^ a.hr_target) true
       (a.hr_target = "darwin/arm64" || a.hr_target = "darwin/amd64" || a.hr_target = "linux/amd64"
        || a.hr_target = "linux/arm64")
   | Ok rs -> Alcotest.failf "expected 2 records, got %d" (List.length rs)
   | Error m -> Alcotest.fail m);
  let second = match run () with Ok r -> r | Error m -> Alcotest.failf "second run failed:\n%s" m in
  expect "second run" second [ "a-web-1 (root@web-1, pool a): no change"; "b-web-2 (root@web-2, pool b): no change" ];
  refuse "second run" second [ "changed (" ];
  (* Certificate mode (step 11a): an operator key in .forge/cluster. *)
  (match Cmd_cluster.run_keygen ~out_dir:(let d = Filename.concat root ".forge/cluster" in mkdir_p d; d) ~force:false () with
   | Ok _ -> () | Error m -> Alcotest.fail m);
  let third = match run () with Ok r -> r | Error m -> Alcotest.failf "certificate run failed:\n%s" m in
  expect "certificate run" third [ "certificate mode"; "certs/a-web-1.cert"; "a.env" ];
  let unit_a = read_file (Host_layout.unit_file layout "a") in
  expect "unit a in certificate mode" unit_a
    [ "Environment=MARCH_NODE_CERT=/etc/march/app/certs/a-web-1.cert";
      "Environment=MARCH_NODE_KEY=/etc/march/app/certs/a-web-1.key";
      "Environment=MARCH_CLUSTER_OPERATOR_PUBKEY=/etc/march/app/certs/operator.pub" ];
  refuse "env file in certificate mode" (read_file (Host_layout.env_file layout "a")) [ "MARCH_CLUSTER_SECRET" ];
  Alcotest.(check string) "operator.pub is the operator's"
    (String.trim (read_file (Filename.concat root ".forge/cluster/operator.pub")))
    (String.trim (read_file (Host_layout.operator_pub layout)));
  let fourth = match run () with Ok r -> r | Error m -> Alcotest.failf "fourth run failed:\n%s" m in
  refuse "certificates are reused" fourth [ "changed (" ]

let test_refuses_non_ssh () =
  with_home @@ fun () ->
  let dir = short_tmp "n" in
  let proj = make_project ~dir ~host_a:"root@web-1" ~host_b:"root@web-2" in
  write_file (Filename.concat proj.Project.root "topology.prod.toml") "[pool.a]\nhosts = [\"root@web-1\"]\n";
  match Host_init.run ~transport:Remote.local ~layout_prefix:dir ~proj ~opts () with
  | Error m -> expect "refusal" m [ "does not say `[backend] kind = \"ssh\"`" ]
  | Ok r -> Alcotest.failf "a non-ssh topology was initialised:\n%s" r

(* ── container ─────────────────────────────────────────────────────────── *)

let sh cmd = Sys.command cmd = 0

let capture cmd =
  let ic = Unix.open_process_in cmd in
  let s = In_channel.input_all ic in
  ignore (Unix.close_process_in ic);
  String.trim s

let skip reason =
  let bar = String.make 72 '*' in
  Printf.eprintf "\n%s\n* SKIP: forge host init container test: %s\n%s\n%!" bar reason bar;
  Alcotest.skip ()

let dockerfile = {|FROM alpine:3.21
RUN apk add --no-cache openssh-server && ssh-keygen -A && mkdir -p /root/.ssh && chmod 700 /root/.ssh \
 && sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config \
 && sed -i 's/^#\?AllowStreamLocalForwarding.*/AllowStreamLocalForwarding yes/' /etc/ssh/sshd_config \
 && passwd -u root 2>/dev/null || true
CMD ["/usr/sbin/sshd", "-D", "-e"]
|}

let image = "forge-host-init-test:1"

let test_container_idempotent () =
  if not (sh "command -v docker >/dev/null 2>&1") then skip "docker is not installed";
  if not (sh "docker info >/dev/null 2>&1") then skip "docker is installed but its daemon is not reachable";
  if not (sh "command -v ssh >/dev/null 2>&1 && command -v ssh-keygen >/dev/null 2>&1") then skip "no ssh client";
  with_home @@ fun () ->
  let dir = short_tmp "c" in
  let ctx = Filename.concat dir "image" in
  mkdir_p ctx;
  write_file (Filename.concat ctx "Dockerfile") dockerfile;
  if not (sh (Printf.sprintf "docker build -q -t %s %s >%s/build.log 2>&1" image ctx dir)) then
    skip (Printf.sprintf "the sshd image did not build (no network?): %s" (read_file (Filename.concat dir "build.log")));
  let key = Filename.concat dir "id_ed25519" in
  if not (sh (Printf.sprintf "ssh-keygen -q -t ed25519 -N '' -f %s" key)) then Alcotest.fail "ssh-keygen";
  let name = Printf.sprintf "forge-host-init-%d" (Unix.getpid ()) in
  if not (sh (Printf.sprintf "docker run -d --name %s -p 127.0.0.1::22 %s >/dev/null" name image)) then
    Alcotest.fail "docker run";
  Fun.protect ~finally:(fun () -> ignore (sh (Printf.sprintf "docker rm -f %s >/dev/null 2>&1" name))) @@ fun () ->
  if not (sh (Printf.sprintf "docker cp %s.pub %s:/root/.ssh/authorized_keys && docker exec %s chown root:root /root/.ssh/authorized_keys"
                key name name)) then Alcotest.fail "installing the key";
  let port = capture (Printf.sprintf "docker port %s 22/tcp | head -1 | sed 's/.*://'" name) in
  let cfg = Filename.concat dir "ssh_config" in
  write_file cfg (Printf.sprintf
                    "Host web-1 web-2\n  HostName 127.0.0.1\n  Port %s\n  User root\n  IdentityFile %s\n\
                    \  IdentitiesOnly yes\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n  LogLevel ERROR\n"
                    port key);
  Unix.putenv "FORGE_SSH_CONFIG" cfg;
  Fun.protect ~finally:(fun () -> Unix.putenv "FORGE_SSH_CONFIG" "") @@ fun () ->
  (* sshd needs a moment after the container starts. *)
  let rec wait n =
    if sh (Printf.sprintf "ssh -F %s web-1 true >/dev/null 2>&1" cfg) then ()
    else if n = 0 then Alcotest.fail "sshd in the container never answered"
    else (Unix.sleepf 0.5; wait (n - 1))
  in
  wait 40;
  (* Both pools' hosts are the one container: a two-pool cluster on one
     machine is refused by the ssh backend, so give pool b no hosts here. *)
  let proj = make_project ~dir ~host_a:"root@web-1" ~host_b:"root@web-1" in
  write_file (Filename.concat proj.Project.root "topology.prod.toml")
    "[pool.a]\nhosts = [{ host = \"root@web-1\", labels = [\"edge\"] }]\n\n[backend]\nkind = \"ssh\"\n";
  let run () = Host_init.run ~proj ~opts () in
  let first = match run () with Ok r -> r | Error m -> Alcotest.failf "first run over ssh failed:\n%s" m in
  print_string first;
  expect "first run" first [ "changed (user march"; "/etc/systemd/system/march-a.service";
                             "note: ufw is not installed" ];
  let exec c = capture (Printf.sprintf "docker exec %s sh -c %s" name (Filename.quote c)) in
  Alcotest.(check string) "the march user" "march" (exec "id -un march");
  Alcotest.(check string) "state dir owner and mode" "march:march 750" (exec "stat -c '%U:%G %a' /var/lib/march/app");
  Alcotest.(check string) "env file owner and mode" "root:march 640" (exec "stat -c '%U:%G %a' /etc/march/app/a.env");
  expect "unit in the container" (exec "cat /etc/systemd/system/march-a.service")
    [ "Environment=MARCH_NODE_NAME=a-web-1"; "Environment=MARCH_DEPLOY_POLICY=/etc/march/app/a.policy"; "User=march" ];
  Alcotest.(check string) "policy" "IO.Console" (exec "cat /etc/march/app/a.policy");
  let arch = exec "uname -m" in
  (match Reconcile.read_host_records ~root:proj.Project.root (Some "prod") with
   | Ok [ r ] ->
     Alcotest.(check string) "recorded target"
       (if arch = "x86_64" then "linux/amd64" else "linux/arm64") r.Reconcile.hr_target;
     Alcotest.(check string) "recorded triple"
       (if arch = "x86_64" then "x86_64-unknown-linux-gnu" else "aarch64-unknown-linux-gnu") r.hr_triple
   | Ok rs -> Alcotest.failf "expected one record, got %d" (List.length rs)
   | Error m -> Alcotest.fail m);
  let second = match run () with Ok r -> r | Error m -> Alcotest.failf "second run over ssh failed:\n%s" m in
  print_string second;
  expect "second run" second [ "a-web-1 (root@web-1, pool a): no change" ];
  refuse "second run" second [ "changed (" ]

let () =
  (* Said before Alcotest captures the test's output, so a skipped
     acceptance test is visible in the console, not only in its log. *)
  if not (sh "command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1") then begin
    let bar = String.make 72 '*' in
    Printf.eprintf "%s\n* SKIP: the forge host init CONTAINER test will be skipped: Docker is absent or its\n\
                    * daemon is not reachable. The acceptance (idempotent against a container host)\n\
                    * is NOT exercised by this run.\n%s\n%!" bar bar
  end;
  Alcotest.run "host-init" [
    ("local", [
        Alcotest.test_case "files, environment, secret and certificate modes; a second run changes nothing" `Quick
          test_local_idempotent;
        Alcotest.test_case "refuses a topology that is not ssh" `Quick test_refuses_non_ssh;
      ]);
    ("container", [
        Alcotest.test_case "over ssh against an sshd container: converges, records the target, idempotent" `Slow
          test_container_idempotent;
      ]);
  ]
