(** cmd_bastion_gen.ml — forge bastion gen schema <Module> <table> field:type ...

    Generate a Depot.Schema module and migration file from CLI arguments. *)

let snake_to_pascal s =
  let parts = String.split_on_char '_' s in
  parts
  |> List.map (fun p ->
       if String.length p = 0 then ""
       else String.capitalize_ascii p)
  |> String.concat ""

let march_type_of = function
  | "string" -> "String"
  | "integer" | "int" -> "Int"
  | "float" -> "Float"
  | "bool" | "boolean" -> "Bool"
  | "uuid" -> "UUID"
  | "datetime" -> "UtcDatetime"
  | "date" -> "Date"
  | "time" -> "Time"
  | "map" | "json" -> "Map"
  | "binary" -> "Binary"
  | other -> other

let parse_field spec =
  match String.split_on_char ':' spec with
  | [name; typ] -> Ok (name, typ)
  | _ -> Error (Printf.sprintf "invalid field spec: %s (expected name:type)" spec)

let schema_source ~app_name ~module_name ~table_name ~fields =
  let field_defs =
    fields
    |> List.map (fun (name, typ) ->
         Printf.sprintf "      %s = \"%s\"" name (march_type_of typ))
    |> String.concat ",\n"
  in
  let field_names =
    fields
    |> List.map (fun (name, _) -> Printf.sprintf "\"%s\"" name)
    |> String.concat ", "
  in
  Printf.sprintf
    {|-- Auto-generated by forge bastion gen schema

mod %s.%s do

fn schema() do
  Depot.Schema.define("%s", {
    fields = {
%s,
      inserted_at = "UtcDatetime",
      updated_at = "UtcDatetime"
    }
  })
end

fn gate(params) do
  Depot.Gate.cast_record(Depot.Schema.blank(schema()), params, [%s])
    |> Depot.Gate.validate_required([%s])
end

fn update_gate(base, params) do
  Depot.Gate.cast_record(base, params, [%s])
end

end
|}
    app_name module_name table_name field_defs field_names field_names field_names

let migration_source ~module_name ~table_name ~fields =
  let col_defs =
    fields
    |> List.map (fun (name, typ) ->
         Printf.sprintf "    %s = (\"%s\", { null = false })" name
           (march_type_of typ))
    |> String.concat ",\n"
  in
  let timestamp = int_of_float (Unix.time ()) in
  let migration_mod = Printf.sprintf "Create%s" module_name in
  Printf.sprintf
    {|-- Auto-generated by forge bastion gen schema

mod Migrations.%s do

fn up() do
  Depot.Migration.create_table("%s", {
    id = ("UUID", { primary_key = true }),
%s,
    inserted_at = ("UtcDatetime", { null = false }),
    updated_at = ("UtcDatetime", { null = false })
  })
end

fn down() do
  Depot.Migration.drop_table("%s")
end

fn version() do
  %d
end

end
|}
    migration_mod table_name col_defs table_name timestamp

let mkdir_p dir =
  let parts = String.split_on_char '/' dir in
  let _ =
    List.fold_left
      (fun acc p ->
        let path = if acc = "" then p else acc ^ "/" ^ p in
        (if path <> "" && not (Sys.file_exists path) then
           Unix.mkdir path 0o755);
        path)
      "" parts
  in
  ()

let write_file path content =
  let oc = open_out path in
  output_string oc content;
  close_out oc

let detect_app_name () =
  let name = Filename.basename (Sys.getcwd ()) in
  snake_to_pascal name

(* ------------------------------------------------------------------ simple substitution helper *)

(** Replace all occurrences of [from] with [to_] in [s]. *)
let str_replace_all ~from ~to_ s =
  let from_len = String.length from in
  if from_len = 0 then s
  else begin
    let buf = Buffer.create (String.length s) in
    let i   = ref 0 in
    let n   = String.length s in
    while !i < n do
      if !i + from_len <= n && String.sub s !i from_len = from then begin
        Buffer.add_string buf to_;
        i := !i + from_len
      end else begin
        Buffer.add_char buf s.[!i];
        incr i
      end
    done;
    Buffer.contents buf
  end

(** Apply a list of [(placeholder, value)] substitutions to [tmpl].
    Placeholders are written as {{KEY}} in the template. *)
let render vars tmpl =
  List.fold_left
    (fun s (k, v) -> str_replace_all ~from:("{{" ^ k ^ "}}") ~to_:v s)
    tmpl vars

(* ------------------------------------------------------------------ json gen templates *)

let json_schema_source ~app_name ~module_name ~table_name ~fields =
  let field_defs =
    fields
    |> List.map (fun (name, typ) ->
         Printf.sprintf "      %s = \"%s\"" name (march_type_of typ))
    |> String.concat ",\n"
  in
  let field_names =
    fields
    |> List.map (fun (name, _) -> Printf.sprintf "\"%s\"" name)
    |> String.concat ", "
  in
  render [
    ("APP",         app_name);
    ("MODULE",      module_name);
    ("TABLE",       table_name);
    ("FIELD_DEFS",  field_defs);
    ("FIELD_NAMES", field_names);
  ] {|-- Auto-generated by forge bastion gen json

mod {{APP}}.{{MODULE}} do

fn schema() do
  Depot.Schema.define("{{TABLE}}", {
    fields = {
{{FIELD_DEFS}},
      inserted_at = "UtcDatetime",
      updated_at = "UtcDatetime"
    }
  })
end

fn gate(params) do
  Depot.Gate.cast_record(Depot.Schema.blank(schema()), params, [{{FIELD_NAMES}}])
    |> Depot.Gate.validate_required([{{FIELD_NAMES}}])
end

fn update_gate(base, params) do
  Depot.Gate.cast_record(base, params, [{{FIELD_NAMES}}])
end

end
|}

let context_source ~app_name ~context_name ~module_name =
  let lower_mod = String.lowercase_ascii module_name in
  render [
    ("APP",      app_name);
    ("CTX",      context_name);
    ("MOD",      module_name);
    ("lmod",     lower_mod);
  ] {|-- Auto-generated by forge bastion gen json

mod {{APP}}.{{CTX}} do

fn list_{{lmod}}s() do
  {{APP}}.Repo.all({{APP}}.{{MOD}}.schema())
end

fn get_{{lmod}}(id) do
  {{APP}}.Repo.get({{APP}}.{{MOD}}.schema(), id)
end

fn get_{{lmod}}!(id) do
  {{APP}}.Repo.get!({{APP}}.{{MOD}}.schema(), id)
end

fn create_{{lmod}}(params) do
  let gate = {{APP}}.{{MOD}}.gate(params)
  match Depot.Gate.is_valid(gate) do
    true  -> {{APP}}.Repo.insert(gate)
    false -> Err(gate)
  end
end

fn update_{{lmod}}({{lmod}}, params) do
  let gate = {{APP}}.{{MOD}}.update_gate({{lmod}}, params)
  match Depot.Gate.is_valid(gate) do
    true  -> {{APP}}.Repo.update(gate)
    false -> Err(gate)
  end
end

fn delete_{{lmod}}({{lmod}}) do
  {{APP}}.Repo.delete({{lmod}})
end

end
|}

let handler_source ~app_name ~context_name ~module_name =
  let lower_mod = String.lowercase_ascii module_name in
  let lower_ctx = String.lowercase_ascii context_name in
  render [
    ("APP",  app_name);
    ("CTX",  context_name);
    ("MOD",  module_name);
    ("lmod", lower_mod);
    ("lctx", lower_ctx);
  ] {|-- Auto-generated by forge bastion gen json

mod {{APP}}.Handlers.{{MOD}}Handler do

alias Bastion.Conn as Conn

-- GET /api/{{lctx}}s
fn index(conn) do
  let items = {{APP}}.{{CTX}}.list_{{lmod}}s()
  Conn.json(conn, 200, items)
end

-- GET /api/{{lctx}}s/:id
fn show(conn, id) do
  match {{APP}}.{{CTX}}.get_{{lmod}}(id) do
    Some(item) ->
      Conn.json(conn, 200, item)
    None ->
      Conn.json(conn, 404, { error = "not found" })
  end
end

-- POST /api/{{lctx}}s
fn create(conn) do
  let params = Conn.json_params(conn)
  match {{APP}}.{{CTX}}.create_{{lmod}}(params) do
    Ok(item) ->
      Conn.json(conn, 201, item)
    Err(gate) ->
      Conn.json(conn, 422, { errors = Depot.Gate.errors(gate) })
  end
end

-- PUT /api/{{lctx}}s/:id
fn update(conn, id) do
  match {{APP}}.{{CTX}}.get_{{lmod}}(id) do
    None ->
      Conn.json(conn, 404, { error = "not found" })
    Some(item) ->
      let params = Conn.json_params(conn)
      match {{APP}}.{{CTX}}.update_{{lmod}}(item, params) do
        Ok(updated) ->
          Conn.json(conn, 200, updated)
        Err(gate) ->
          Conn.json(conn, 422, { errors = Depot.Gate.errors(gate) })
      end
  end
end

-- DELETE /api/{{lctx}}s/:id
fn delete(conn, id) do
  match {{APP}}.{{CTX}}.get_{{lmod}}(id) do
    None ->
      Conn.json(conn, 404, { error = "not found" })
    Some(item) ->
      {{APP}}.{{CTX}}.delete_{{lmod}}(item)
      Conn.json(conn, 204, {})
  end
end

-- Fallback: 404 JSON response for unmatched routes
fn not_found(conn) do
  Conn.json(conn, 404, { error = "not found" })
end

end
|}

let handler_test_source ~app_name ~module_name =
  let lower_mod = String.lowercase_ascii module_name in
  render [
    ("APP",  app_name);
    ("MOD",  module_name);
    ("lmod", lower_mod);
  ] {|-- Auto-generated by forge bastion gen json

mod {{APP}}.Handlers.Test{{MOD}}Handler do

describe "{{MOD}}Handler" do

  test "index returns list of {{lmod}}s" do
    assert true
  end

  test "show returns a single {{lmod}}" do
    assert true
  end

  test "show returns 404 for missing {{lmod}}" do
    assert true
  end

  test "create with valid params returns 201" do
    assert true
  end

  test "create with invalid params returns 422" do
    assert true
  end

  test "update with valid params returns 200" do
    assert true
  end

  test "update with invalid params returns 422" do
    assert true
  end

  test "delete removes {{lmod}} and returns 204" do
    assert true
  end

end

end
|}

let print_route_snippet ~app_name ~module_name ~lower_ctx =
  let lower_app = String.lowercase_ascii app_name in
  let plural    = lower_ctx ^ "s" in
  Printf.printf
{|
Add to your router (lib/%s/router.march):

  -- ROUTE: GET /api/%s
  (:get,    Cons("api", Cons("%s", Nil))) ->
    %s.Handlers.%sHandler.index(conn)

  -- ROUTE: GET /api/%s/:id
  (:get,    Cons("api", Cons("%s", Cons(id, Nil)))) ->
    %s.Handlers.%sHandler.show(conn, id)

  -- ROUTE: POST /api/%s
  (:post,   Cons("api", Cons("%s", Nil))) ->
    %s.Handlers.%sHandler.create(conn)

  -- ROUTE: PUT /api/%s/:id
  (:put,    Cons("api", Cons("%s", Cons(id, Nil)))) ->
    %s.Handlers.%sHandler.update(conn, id)

  -- ROUTE: DELETE /api/%s/:id
  (:delete, Cons("api", Cons("%s", Cons(id, Nil)))) ->
    %s.Handlers.%sHandler.delete(conn, id)

|}
    lower_app
    plural plural  app_name module_name
    plural plural  app_name module_name
    plural plural  app_name module_name
    plural plural  app_name module_name
    plural plural  app_name module_name

(* ------------------------------------------------------------------ run_json *)

let run_json context_name module_name field_specs =
  let fields_result = List.map parse_field field_specs in
  let errors =
    List.filter_map
      (function Error e -> Some e | Ok _ -> None)
      fields_result
  in
  if errors <> [] then Error (String.concat "\n" errors)
  else
    let fields =
      List.filter_map
        (function Ok f -> Some f | Error _ -> None)
        fields_result
    in
    let app_name    = detect_app_name () in
    let lower_app   = String.lowercase_ascii app_name in
    let lower_mod   = String.lowercase_ascii module_name in
    let lower_ctx   = String.lowercase_ascii context_name in
    let table_name  = lower_mod ^ "s" in

    (* 1 — Schema *)
    let schema_dir = Filename.concat "src" (Filename.concat "app" "schemas") in
    mkdir_p schema_dir;
    let schema_file = Filename.concat schema_dir (lower_mod ^ ".march") in
    write_file schema_file
      (json_schema_source ~app_name ~module_name ~table_name ~fields);
    Printf.printf "* creating %s\n%!" schema_file;

    (* 2 — Migration *)
    let migration_dir =
      Filename.concat "priv" (Filename.concat "depot" "migrations")
    in
    mkdir_p migration_dir;
    let timestamp = int_of_float (Unix.time ()) in
    let migration_file =
      Filename.concat migration_dir
        (Printf.sprintf "%d_create_%s.march" timestamp table_name)
    in
    write_file migration_file
      (migration_source ~module_name ~table_name ~fields);
    Printf.printf "* creating %s\n%!" migration_file;

    (* 3 — Context *)
    let context_dir = Filename.concat "src" (Filename.concat "app" "contexts") in
    mkdir_p context_dir;
    let context_file = Filename.concat context_dir (lower_ctx ^ ".march") in
    write_file context_file
      (context_source ~app_name ~context_name ~module_name);
    Printf.printf "* creating %s\n%!" context_file;

    (* 4 — Handler *)
    let handler_dir = Filename.concat "src" (Filename.concat "app" "handlers") in
    mkdir_p handler_dir;
    let handler_file =
      Filename.concat handler_dir (lower_mod ^ "_handler.march")
    in
    write_file handler_file
      (handler_source ~app_name ~context_name ~module_name);
    Printf.printf "* creating %s\n%!" handler_file;

    (* 5 — Test *)
    let test_dir = Filename.concat "test" "handlers" in
    mkdir_p test_dir;
    let test_file =
      Filename.concat test_dir (lower_mod ^ "_handler_test.march")
    in
    write_file test_file
      (handler_test_source ~app_name ~module_name);
    Printf.printf "* creating %s\n%!" test_file;

    (* 6 — Print route snippet *)
    let _ = lower_app in
    print_route_snippet ~app_name ~module_name ~lower_ctx;

    Ok ()

(* ------------------------------------------------------------------ run_schema *)

let run_schema module_name table_name field_specs =
  let fields_result = List.map parse_field field_specs in
  let errors =
    List.filter_map
      (function Error e -> Some e | Ok _ -> None)
      fields_result
  in
  if errors <> [] then Error (String.concat "\n" errors)
  else
    let fields =
      List.filter_map
        (function Ok f -> Some f | Error _ -> None)
        fields_result
    in
    let app_name = detect_app_name () in

    (* Generate schema file *)
    let schema_dir = Filename.concat "lib" (String.lowercase_ascii app_name) in
    mkdir_p schema_dir;
    let schema_file =
      Filename.concat schema_dir
        (String.lowercase_ascii module_name ^ ".march")
    in
    let schema_content =
      schema_source ~app_name ~module_name ~table_name ~fields
    in
    write_file schema_file schema_content;
    Printf.printf "* creating %s\n%!" schema_file;

    (* Generate migration file *)
    let migration_dir =
      Filename.concat "priv" (Filename.concat "depot" "migrations")
    in
    mkdir_p migration_dir;
    let timestamp = int_of_float (Unix.time ()) in
    let migration_file =
      Filename.concat migration_dir
        (Printf.sprintf "%d_create_%s.march" timestamp table_name)
    in
    let migration_content =
      migration_source ~module_name ~table_name ~fields
    in
    write_file migration_file migration_content;
    Printf.printf "* creating %s\n%!" migration_file;

    Ok ()
