(** cmd_bastion_gen.ml — forge bastion gen schema <Module> <table> field:type ...

    Generate a Depot.Schema module and migration file from CLI arguments. *)

let snake_to_pascal s =
  let parts = String.split_on_char '_' s in
  parts
  |> List.map (fun p ->
       if String.length p = 0 then ""
       else String.capitalize_ascii p)
  |> String.concat ""

let march_type_of = function
  | "string" -> "String"
  | "integer" | "int" -> "Int"
  | "float" -> "Float"
  | "bool" | "boolean" -> "Bool"
  | "uuid" -> "UUID"
  | "datetime" -> "UtcDatetime"
  | "date" -> "Date"
  | "time" -> "Time"
  | "map" | "json" -> "Map"
  | "binary" -> "Binary"
  | other -> other

let parse_field spec =
  match String.split_on_char ':' spec with
  | [name; typ] -> Ok (name, typ)
  | _ -> Error (Printf.sprintf "invalid field spec: %s (expected name:type)" spec)

let schema_source ~app_name ~module_name ~table_name ~fields =
  let field_defs =
    fields
    |> List.map (fun (name, typ) ->
         Printf.sprintf "      %s = \"%s\"" name (march_type_of typ))
    |> String.concat ",\n"
  in
  let field_names =
    fields
    |> List.map (fun (name, _) -> Printf.sprintf "\"%s\"" name)
    |> String.concat ", "
  in
  Printf.sprintf
    {|-- Auto-generated by forge bastion gen schema

mod %s.%s do

fn schema() do
  Depot.Schema.define("%s", {
    fields = {
%s,
      inserted_at = "UtcDatetime",
      updated_at = "UtcDatetime"
    }
  })
end

fn gate(params) do
  Depot.Gate.cast_record(Depot.Schema.blank(schema()), params, [%s])
    |> Depot.Gate.validate_required([%s])
end

fn update_gate(base, params) do
  Depot.Gate.cast_record(base, params, [%s])
end

end
|}
    app_name module_name table_name field_defs field_names field_names field_names

let migration_source ~module_name ~table_name ~fields =
  let col_defs =
    fields
    |> List.map (fun (name, typ) ->
         Printf.sprintf "    %s = (\"%s\", { null = false })" name
           (march_type_of typ))
    |> String.concat ",\n"
  in
  let timestamp = int_of_float (Unix.time ()) in
  let migration_mod = Printf.sprintf "Create%s" module_name in
  Printf.sprintf
    {|-- Auto-generated by forge bastion gen schema

mod Migrations.%s do

fn up() do
  Depot.Migration.create_table("%s", {
    id = ("UUID", { primary_key = true }),
%s,
    inserted_at = ("UtcDatetime", { null = false }),
    updated_at = ("UtcDatetime", { null = false })
  })
end

fn down() do
  Depot.Migration.drop_table("%s")
end

fn version() do
  %d
end

end
|}
    migration_mod table_name col_defs table_name timestamp

let mkdir_p dir =
  let parts = String.split_on_char '/' dir in
  let _ =
    List.fold_left
      (fun acc p ->
        let path = if acc = "" then p else acc ^ "/" ^ p in
        (if path <> "" && not (Sys.file_exists path) then
           Unix.mkdir path 0o755);
        path)
      "" parts
  in
  ()

let write_file path content =
  let oc = open_out path in
  output_string oc content;
  close_out oc

let detect_app_name () =
  let name = Filename.basename (Sys.getcwd ()) in
  snake_to_pascal name

let run_schema module_name table_name field_specs =
  let fields_result = List.map parse_field field_specs in
  let errors =
    List.filter_map
      (function Error e -> Some e | Ok _ -> None)
      fields_result
  in
  if errors <> [] then Error (String.concat "\n" errors)
  else
    let fields =
      List.filter_map
        (function Ok f -> Some f | Error _ -> None)
        fields_result
    in
    let app_name = detect_app_name () in

    (* Generate schema file *)
    let schema_dir = Filename.concat "lib" (String.lowercase_ascii app_name) in
    mkdir_p schema_dir;
    let schema_file =
      Filename.concat schema_dir
        (String.lowercase_ascii module_name ^ ".march")
    in
    let schema_content =
      schema_source ~app_name ~module_name ~table_name ~fields
    in
    write_file schema_file schema_content;
    Printf.printf "* creating %s\n%!" schema_file;

    (* Generate migration file *)
    let migration_dir =
      Filename.concat "priv" (Filename.concat "depot" "migrations")
    in
    mkdir_p migration_dir;
    let timestamp = int_of_float (Unix.time ()) in
    let migration_file =
      Filename.concat migration_dir
        (Printf.sprintf "%d_create_%s.march" timestamp table_name)
    in
    let migration_content =
      migration_source ~module_name ~table_name ~fields
    in
    write_file migration_file migration_content;
    Printf.printf "* creating %s\n%!" migration_file;

    Ok ()
