(** forge ffi gen-c <file.march> [-o out.c]

    Generate a C shim skeleton from the `extern` blocks in a March file.  For
    each `extern fn`, emits a C function with the right signature and the
    marshalling boilerplate prefilled (borrow slices for String/Bytes params,
    Option/Result/resource hints, a typed return stub), leaving a TODO for the
    actual library call.  The "declare in March, generate the C glue" direction
    from specs/2026-06-19-c-ffi-abi-design.md §17. *)

module Ast = March_ast.Ast

let parse_file path : (Ast.decl list, string) result =
  try
    let ic  = open_in path in
    let src = really_input_string ic (in_channel_length ic) in
    close_in ic;
    let lexbuf = Lexing.from_string src in
    lexbuf.Lexing.lex_curr_p <-
      { lexbuf.Lexing.lex_curr_p with Lexing.pos_fname = path };
    let m = March_parser.Parser.module_
        (March_parser.Token_filter.make March_lexer.Lexer.token) lexbuf in
    Ok m.Ast.mod_decls
  with
  | Sys_error msg -> Error msg
  | exn -> Error (Printexc.to_string exn)

(* ── Type classification ─────────────────────────────────────────────────── *)

let con_name = function
  | Ast.TyCon ({ Ast.txt; _ }, _) -> Some txt
  | _ -> None

(* C type for an extern parameter / return position. *)
let c_type ~ret (t : Ast.ty) : string =
  match con_name t with
  | Some ("Int" | "Char" | "Bool") -> "int64_t"
  | Some "Float"                    -> "double"
  | Some "Unit" when ret           -> "void"
  | _                              -> "march_value"  (* String/Bytes/Option/Result/resource *)

let is_string_ty t = match con_name t with Some ("String" | "Bytes") -> true | _ -> false

(* ── Skeleton generation ─────────────────────────────────────────────────── *)

let gen_fn (lib : string) (consumed : bool list) (ef : Ast.extern_fn) : string =
  let c_name = match ef.Ast.ef_symbol with
    | Some s -> s
    | None   -> lib ^ "_" ^ ef.Ast.ef_name.Ast.txt in
  let consumed_of i = match List.nth_opt consumed i with Some b -> b | None -> false in
  let params =
    List.map (fun (n, t) ->
      Printf.sprintf "%s %s" (c_type ~ret:false t) n.Ast.txt) ef.Ast.ef_params in
  let b = Buffer.create 256 in
  Buffer.add_string b (Printf.sprintf "/* %s%s(%s) : %s */\n"
    (if ef.Ast.ef_blocking then "blocking " else "")
    ef.Ast.ef_name.Ast.txt
    (String.concat ", " (List.map (fun (n,t) ->
       Printf.sprintf "%s : %s" n.Ast.txt (Ast.show_ty t)) ef.Ast.ef_params))
    (Ast.show_ty ef.Ast.ef_ret_ty));
  Buffer.add_string b (Printf.sprintf "%s %s(%s) {\n"
    (c_type ~ret:true ef.Ast.ef_ret_ty) c_name (String.concat ", " params));
  (* Per-param marshalling hints. *)
  List.iteri (fun i (n, t) ->
    let nm = n.Ast.txt in
    if is_string_ty t then
      Buffer.add_string b (Printf.sprintf
        "    march_slice %s_s = march_str_borrow(%s); (void)%s_s;  /* %s_s.ptr, %s_s.len */\n"
        nm nm nm nm nm)
    else (match con_name t with
      | Some ("Int" | "Char" | "Bool" | "Float" | "Option" | "Result") -> ()
      | Some other ->
        (* opaque/resource handle *)
        Buffer.add_string b (Printf.sprintf
          "    /* %s p = march_resource_get(%s, %s_TID);%s */\n"
          (other ^ " *") nm (String.uppercase_ascii other)
          (if consumed_of i then "  // consume: march_drop(" ^ nm ^ ") when done" else ""))
      | None -> ())
  ) ef.Ast.ef_params;
  Buffer.add_string b "    /* TODO: call the C library and build the result. */\n";
  (match con_name ef.Ast.ef_ret_ty with
   | Some "Unit"   -> ()
   | Some "Result" -> Buffer.add_string b
       "    return march_err(march_str_new((const uint8_t *)\"not implemented\", 15));  /* or march_ok(v) */\n"
   | Some "Option" -> Buffer.add_string b "    return march_none();  /* or march_some(v) */\n"
   | _ when is_string_ty ef.Ast.ef_ret_ty -> Buffer.add_string b
       "    return march_str_new((const uint8_t *)\"\", 0);\n"
   | Some "Float"  -> Buffer.add_string b "    return 0.0;\n"
   | _             -> Buffer.add_string b "    return 0;\n");
  Buffer.add_string b "}\n";
  Buffer.contents b

let gen_c (decls : Ast.decl list) : string =
  let b = Buffer.create 1024 in
  Buffer.add_string b
    "/* Generated by `forge ffi gen-c` — fill in the TODOs, then list this file\n\
    \   under [ffi] sources in forge.toml. */\n\
     #include \"march_ffi.h\"\n#include <stdint.h>\n\n";
  List.iter (function
    | Ast.DExtern (edef, _) ->
      List.iter (fun (ef : Ast.extern_fn) ->
        Buffer.add_string b (gen_fn edef.Ast.ext_lib_name ef.Ast.ef_param_consumed ef);
        Buffer.add_char b '\n')
        edef.Ast.ext_fns
    | _ -> ()) decls;
  Buffer.contents b

let run ~file ~out : (unit, string) result =
  match parse_file file with
  | Error e -> Error e
  | Ok decls ->
    if not (List.exists (function Ast.DExtern _ -> true | _ -> false) decls) then
      Error (Printf.sprintf "no `extern` blocks found in %s" file)
    else begin
      let c = gen_c decls in
      (match out with
       | Some path ->
         let oc = open_out path in output_string oc c; close_out oc;
         Printf.printf "wrote %s\n" path
       | None -> print_string c);
      Ok ()
    end
