(** gen_auth.ml — forge bastion gen auth

    Generates authentication boilerplate for a Bastion web application.
    Modelled on Phoenix phx.gen.auth — produces ready-to-use files that
    developers can customise.

    Files created
    ─────────────
      lib/<app>/accounts/user.march               User schema + gate fns
      lib/<app>/accounts/user_token.march         Session/email token schema
      lib/<app>/accounts/user_notifier.march      Email notification stubs
      lib/<app>/accounts.march                    Accounts context (business logic)
      lib/<app>/auth.march                        Auth middleware plugs
      lib/<app>/controllers/auth/registration_controller.march
      lib/<app>/controllers/auth/session_controller.march
      lib/<app>/controllers/auth/user_settings_controller.march
      lib/<app>/controllers/auth/confirmation_controller.march
      priv/depot/migrations/<ts>_create_users.march
      priv/depot/migrations/<ts+1>_create_user_tokens.march
      test/support/accounts_fixtures.march        Test factory helpers *)

(* ------------------------------------------------------------------ helpers *)

let write_file path content =
  let oc = open_out path in
  output_string oc content;
  close_out oc

let mkdir_p dir =
  let parts = String.split_on_char '/' dir in
  let _ =
    List.fold_left
      (fun acc p ->
        let path = if acc = "" then p else acc ^ "/" ^ p in
        (if path <> "" && not (Sys.file_exists path) then
           Unix.mkdir path 0o755);
        path)
      "" parts
  in
  ()

let snake_to_pascal s =
  String.split_on_char '_' s
  |> List.filter (fun p -> p <> "")
  |> List.map String.capitalize_ascii
  |> String.concat ""

let detect_app_name () =
  let name = Filename.basename (Sys.getcwd ()) in
  snake_to_pascal name

(* ---------------------------------------------------------------- templates *)

(** lib/<app>/accounts/user.march *)
let user_schema_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth
-- Represents a registered user account.
-- Passwords are hashed with PBKDF2-SHA256 via Crypto.hash_password.

mod %s.Accounts.User do

alias Depot.Gate as Gate
alias Depot.Schema as Schema

fn schema() do
  Schema.define("users", {
    fields = {
      email = "String",
      hashed_password = "String",
      confirmed_at = ("UtcDatetime", { null = true }),
      inserted_at = "UtcDatetime",
      updated_at = "UtcDatetime"
    }
  })
end

-- ---------------------------------------------------------------------------
-- Gates
-- ---------------------------------------------------------------------------

-- Gate for new user registration.
-- Validates email format, uniqueness, and password strength.
-- Does NOT hash the password — call hash_password/1 after validation.
fn registration_gate(params) do
  Gate.cast(params, ["email", "password"])
    |> Gate.validate_required(["email", "password"])
    |> validate_email()
    |> validate_password()
end

-- Gate for updating a user's email address.
fn update_email_gate(user, params) do
  Gate.cast_record(user, params, ["email"])
    |> Gate.validate_required(["email"])
    |> validate_email()
end

-- Gate for updating a user's password.
fn update_password_gate(user, params) do
  Gate.cast_record(user, params, ["password", "password_confirmation"])
    |> Gate.validate_required(["password", "password_confirmation"])
    |> validate_password()
    |> Gate.validate_confirmation("password")
end

-- ---------------------------------------------------------------------------
-- Password helpers
-- ---------------------------------------------------------------------------

-- Hash the plain-text "password" change in a gate and replace it with
-- "hashed_password".  Returns the gate unchanged if no password change exists.
fn hash_password(gate) do
  match Gate.get_change(gate, "password") do
  None -> gate
  Some(password) ->
    let hashed = Crypto.hash_password(password)
    Gate.put_change(gate, "hashed_password", hashed)
      |> Gate.delete_change("password")
  end
end

-- Return true if `password` matches the stored hash on `user`.
fn valid_password(user, password) do
  Crypto.verify_password(password, user.hashed_password)
end

-- ---------------------------------------------------------------------------
-- Private validators
-- ---------------------------------------------------------------------------

pfn validate_email(gate) do
  Gate.validate_format(gate, "email", ".+@.+\\..+")
    |> Gate.validate_length("email", [LenMax(160)])
    |> Gate.unique_constraint("email",
        [ConstraintName("users_email_index"),
         ConstraintMessage("has already been taken")])
end

pfn validate_password(gate) do
  Gate.validate_length(gate, "password", [LenMin(12), LenMax(72)])
end

end
|} pascal

(** lib/<app>/accounts/user_token.march *)
let user_token_schema_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth
-- Stores session tokens and email-based tokens (confirmation, password reset).
-- Session tokens are random hex strings stored directly.
-- Email tokens are stored as their SHA-256 hash; the raw token is emailed.

mod %s.Accounts.UserToken do

alias Depot.Gate as Gate
alias Depot.Schema as Schema

let session_validity_days    = 60
let confirm_validity_days    = 7
let change_email_validity_days = 7
let reset_validity_days      = 1

fn schema() do
  Schema.define("user_tokens", {
    fields = {
      user_id    = "UUID",
      token      = "String",
      context    = "String",
      sent_to    = ("String", { null = true }),
      inserted_at = "UtcDatetime"
    }
  })
end

-- Build a session token gate.
-- Returns (raw_token, gate) — insert the gate, hand the raw token to the browser.
fn build_session_token(user) do
  let token = Crypto.random_hex(32)
  let gate = Gate.cast(
    [("user_id", user.id), ("token", token), ("context", "session")],
    ["user_id", "token", "context"]
  )
  (token, gate)
end

-- Build an email token gate (confirmation, password reset, email change).
-- Returns (raw_token, gate) — insert the gate, email the raw token.
-- The stored token is the SHA-256 hash of the raw token.
fn build_email_token(user, context) do
  let token = Crypto.random_hex(32)
  let hashed = Crypto.sha256(token)
  let gate = Gate.cast(
    [("user_id", user.id), ("token", hashed),
     ("context", context), ("sent_to", user.email)],
    ["user_id", "token", "context", "sent_to"]
  )
  (token, gate)
end

end
|} pascal

(** lib/<app>/accounts/user_notifier.march *)
let user_notifier_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth
-- Stubs for transactional emails sent during the auth flow.
-- Replace the `println` calls with your actual mailer integration.

mod %s.Accounts.UserNotifier do

fn deliver_welcome(user) do
  println("TODO: send welcome email to " ++ user.email)
  :ok
end

fn deliver_confirmation_instructions(user, confirmation_url) do
  println("TODO: send confirmation email to " ++ user.email)
  println("  Confirmation URL: " ++ confirmation_url)
  :ok
end

fn deliver_reset_password_instructions(user, reset_url) do
  println("TODO: send password reset email to " ++ user.email)
  println("  Reset URL: " ++ reset_url)
  :ok
end

fn deliver_update_email_instructions(user, update_url) do
  println("TODO: send email change notification to " ++ user.email)
  println("  Update URL: " ++ update_url)
  :ok
end

end
|} pascal

(** priv/depot/migrations/<ts>_create_users.march *)
let users_migration_source ts =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth

mod Migrations.CreateUsers do

fn up() do
  Depot.Migration.create_table("users", {
    id             = ("UUID",        { primary_key = true }),
    email          = ("String",      { null = false }),
    hashed_password = ("String",     { null = false }),
    confirmed_at   = ("UtcDatetime", { null = true }),
    inserted_at    = ("UtcDatetime", { null = false }),
    updated_at     = ("UtcDatetime", { null = false })
  })
  Depot.Migration.create_index("users", ["email"], { unique = true })
end

fn down() do
  Depot.Migration.drop_table("users")
end

fn version() do
  %d
end

end
|} ts

(** priv/depot/migrations/<ts+1>_create_user_tokens.march *)
let user_tokens_migration_source ts =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth

mod Migrations.CreateUserTokens do

fn up() do
  Depot.Migration.create_table("user_tokens", {
    id          = ("UUID",        { primary_key = true }),
    user_id     = ("UUID",        { null = false }),
    token       = ("String",      { null = false }),
    context     = ("String",      { null = false }),
    sent_to     = ("String",      { null = true }),
    inserted_at = ("UtcDatetime", { null = false })
  })
  Depot.Migration.create_index("user_tokens", ["token"],            { unique = true })
  Depot.Migration.create_index("user_tokens", ["context", "sent_to"], {})
  -- Foreign key: deleting a user cascades to their tokens
  Depot.Migration.execute("ALTER TABLE user_tokens ADD CONSTRAINT user_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE")
end

fn down() do
  Depot.Migration.drop_table("user_tokens")
end

fn version() do
  %d
end

end
|} ts

(** lib/<app>/accounts.march — Accounts context (all business logic) *)
let accounts_context_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth
-- The Accounts context is the public API for user management.
-- All callers should go through this module, not the schemas directly.

mod %s.Accounts do

alias %s.Accounts.User as User
alias %s.Accounts.UserToken as UserToken
alias %s.Accounts.UserNotifier as UserNotifier
alias Depot.Repo as Repo
alias Depot.Gate as Gate
alias Depot.Query as Q

-- ---------------------------------------------------------------------------
-- User lookups
-- ---------------------------------------------------------------------------

fn get_user(id) do
  Repo.get(User.schema(), id)
end

fn get_user_by_email(email) do
  Repo.get_by(User.schema(), { email = email })
end

-- Returns Some(user) if the email/password combination is valid, None otherwise.
fn get_user_by_email_and_password(email, password) do
  match Repo.get_by(User.schema(), { email = email }) do
  None -> None
  Some(user) ->
    if User.valid_password(user, password) do
      Some(user)
    else None end
  end
end

-- ---------------------------------------------------------------------------
-- Registration
-- ---------------------------------------------------------------------------

-- Register a new user.  Returns Ok(user) or Err(gate) with validation errors.
fn register_user(params) do
  let gate = User.registration_gate(params)
  if Gate.is_valid(gate) do
    let final_gate = User.hash_password(gate)
    match Repo.insert(User.schema(), final_gate) do
    Ok(user) ->
      UserNotifier.deliver_welcome(user)
      Ok(user)
    Err(g) -> Err(g)
    end
  else Err(gate) end
end

-- Build an empty registration gate (useful for rendering a blank form).
fn change_user_registration(attrs) do
  User.registration_gate(attrs)
end

-- ---------------------------------------------------------------------------
-- Email + password updates
-- ---------------------------------------------------------------------------

fn update_user_email(user, params) do
  let gate = User.update_email_gate(user, params)
  if Gate.is_valid(gate) do
    Repo.update(User.schema(), gate)
  else Err(gate) end
end

fn update_user_password(user, params) do
  let gate = User.update_password_gate(user, params)
  if Gate.is_valid(gate) do
    let final_gate = User.hash_password(gate)
    match Repo.update(User.schema(), final_gate) do
    Ok(updated_user) ->
      delete_all_user_tokens(user, "session")
      Ok(updated_user)
    Err(g) -> Err(g)
    end
  else Err(gate) end
end

-- Build a gate for the settings form (no persistence, just for rendering).
fn change_user_password(user) do
  User.update_password_gate(user, [])
end

-- ---------------------------------------------------------------------------
-- Session tokens
-- ---------------------------------------------------------------------------

fn create_session_token(user) do
  let (token, gate) = UserToken.build_session_token(user)
  match Repo.insert(UserToken.schema(), gate) do
  Ok(_) -> Ok(token)
  Err(g) -> Err(g)
  end
end

fn get_user_by_session_token(token) do
  match Repo.get_by(UserToken.schema(), { token = token, context = "session" }) do
  None -> None
  Some(tok) -> Repo.get(User.schema(), tok.user_id)
  end
end

fn delete_session_token(token) do
  match Repo.get_by(UserToken.schema(), { token = token, context = "session" }) do
  None -> :ok
  Some(tok) ->
    Repo.delete(UserToken.schema(), tok.id)
    :ok
  end
end

-- ---------------------------------------------------------------------------
-- Email confirmation
-- ---------------------------------------------------------------------------

fn deliver_user_confirmation_instructions(user, url_fn) do
  let (token, gate) = UserToken.build_email_token(user, "confirm")
  match Repo.insert(UserToken.schema(), gate) do
  Ok(_) ->
    UserNotifier.deliver_confirmation_instructions(user, url_fn(token))
    :ok
  Err(_) -> :error
  end
end

fn confirm_user(token_str) do
  let hashed = Crypto.sha256(token_str)
  match Repo.get_by(UserToken.schema(), { token = hashed, context = "confirm" }) do
  None -> Err("invalid or expired confirmation token")
  Some(tok) ->
    match Repo.get(User.schema(), tok.user_id) do
    None -> Err("user not found")
    Some(user) ->
      let now = UtcDatetime.now()
      let gate = Gate.cast_record(user, { confirmed_at = now }, ["confirmed_at"])
      match Repo.update(User.schema(), gate) do
      Ok(confirmed_user) ->
        Repo.delete(UserToken.schema(), tok.id)
        Ok(confirmed_user)
      Err(g) -> Err(g)
      end
    end
  end
end

-- ---------------------------------------------------------------------------
-- Password reset
-- ---------------------------------------------------------------------------

fn deliver_user_reset_password_instructions(user, url_fn) do
  let (token, gate) = UserToken.build_email_token(user, "reset_password")
  match Repo.insert(UserToken.schema(), gate) do
  Ok(_) ->
    UserNotifier.deliver_reset_password_instructions(user, url_fn(token))
    :ok
  Err(_) -> :error
  end
end

fn get_user_by_reset_password_token(token_str) do
  let hashed = Crypto.sha256(token_str)
  match Repo.get_by(UserToken.schema(), { token = hashed, context = "reset_password" }) do
  None -> None
  Some(tok) -> Repo.get(User.schema(), tok.user_id)
  end
end

fn reset_user_password(user, params) do
  let gate = User.update_password_gate(user, params)
  if Gate.is_valid(gate) do
    let final_gate = User.hash_password(gate)
    match Repo.update(User.schema(), final_gate) do
    Ok(updated_user) ->
      delete_all_user_tokens(user, "reset_password")
      Ok(updated_user)
    Err(g) -> Err(g)
    end
  else Err(gate) end
end

-- ---------------------------------------------------------------------------
-- Private helpers
-- ---------------------------------------------------------------------------

pfn delete_all_user_tokens(user, context) do
  let tokens = Q.from(UserToken.schema())
    |> Q.where_(fn tok -> tok.user_id == user.id && tok.context == context)
    |> Q.execute(Repo)
  List.each(tokens, fn tok -> Repo.delete(UserToken.schema(), tok.id))
end

end
|} pascal pascal pascal pascal

(** lib/<app>/auth.march — middleware plugs *)
let auth_middleware_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth
-- Auth middleware plugs for the router pipeline.
--
-- Usage in your router:
--
--   alias %s.Auth as Auth
--
--   -- Load current user on every request:
--   |> Bastion.Middleware.pipeline([Auth.load_current_user])
--
--   -- Protect specific routes:
--   |> Bastion.Middleware.pipeline([Auth.require_authenticated_user])

mod %s.Auth do

alias %s.Accounts as Accounts
alias HttpServer as H

-- Load the current user from the session token and assign to conn.
-- Sets "current_user" assign to Some(user) or None.
-- Include this in every pipeline that needs to know who is logged in.
fn load_current_user(conn) do
  match H.get_session(conn, "user_token") do
  None ->
    H.assign(conn, "current_user", None)
  Some(token) ->
    let user_opt = Accounts.get_user_by_session_token(token)
    H.assign(conn, "current_user", user_opt)
  end
end

-- Require the user to be authenticated.
-- Redirects to /users/log_in with a flash message if not logged in.
-- Use this to protect routes that require authentication.
fn require_authenticated_user(conn) do
  match H.get_assign(conn, "current_user") do
  Some(_) -> conn
  None ->
    conn
      |> H.put_flash("error", "You must log in to access this page.")
      |> H.redirect("/users/log_in")
      |> H.halt()
  end
end

-- Redirect authenticated users away from guest-only pages (login, register).
-- Use this on the login and registration pages.
fn redirect_if_authenticated(conn) do
  match H.get_assign(conn, "current_user") do
  None -> conn
  Some(_) ->
    conn
      |> H.redirect("/")
      |> H.halt()
  end
end

end
|} pascal pascal pascal

(** lib/<app>/controllers/auth/registration_controller.march *)
let registration_controller_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth

mod %s.Controllers.Auth.RegistrationController do

alias %s.Accounts as Accounts
alias HttpServer as H

fn new(conn) do
  let gate = Accounts.change_user_registration([])
  H.html(conn, 200, render_form(gate, ""))
end

fn create(conn) do
  let params = H.body_params(conn)
  match Accounts.register_user(params) do
  Ok(_user) ->
    conn
      |> H.put_flash("info", "Account created! Please check your email to confirm your account.")
      |> H.redirect("/users/log_in")
  Err(gate) ->
    H.html(conn, 422, render_form(gate, ""))
  end
end

-- TODO: replace with your ~H template
pfn render_form(_gate, _error) do
  ~H"""<div class="auth-form">
  <h1>Create an account</h1>
  <form method="post" action="/users/register">
    <label>Email <input type="email" name="email" required></label>
    <label>Password <input type="password" name="password" required minlength="12"></label>
    <button type="submit">Register</button>
  </form>
  <p><a href="/users/log_in">Already have an account? Log in</a></p>
</div>"""
end

end
|} pascal pascal

(** lib/<app>/controllers/auth/session_controller.march *)
let session_controller_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth

mod %s.Controllers.Auth.SessionController do

alias %s.Accounts as Accounts
alias HttpServer as H

fn new(conn) do
  H.html(conn, 200, render_form(""))
end

fn create(conn) do
  let params = H.body_params(conn)
  let email    = List.find_value(params, fn (k, v) -> if k == "email" do Some(v) else None end)
  let password = List.find_value(params, fn (k, v) -> if k == "password" do Some(v) else None end)
  let email_str    = match email    do Some(e) -> e | None -> "" end
  let password_str = match password do Some(p) -> p | None -> "" end
  match Accounts.get_user_by_email_and_password(email_str, password_str) do
  None ->
    conn
      |> H.put_flash("error", "Invalid email or password.")
      |> H.html(200, render_form("Invalid email or password."))
  Some(user) ->
    match Accounts.create_session_token(user) do
    Ok(token) ->
      conn
        |> H.put_session("user_token", token)
        |> H.put_flash("info", "Welcome back!")
        |> H.redirect("/")
    Err(_) ->
      H.html(conn, 500, "Internal error")
    end
  end
end

fn delete(conn) do
  match H.get_session(conn, "user_token") do
  Some(token) -> Accounts.delete_session_token(token)
  None -> :ok
  end
  conn
    |> H.clear_session()
    |> H.put_flash("info", "Logged out successfully.")
    |> H.redirect("/")
end

-- TODO: replace with your ~H template
pfn render_form(error) do
  let error_html = if error == "" do ""
                   else "<p class=\"error\">" ++ error ++ "</p>" end
  ~H"""<div class="auth-form">
  <h1>Log in</h1>
  ${error_html}
  <form method="post" action="/users/log_in">
    <label>Email <input type="email" name="email" required></label>
    <label>Password <input type="password" name="password" required></label>
    <button type="submit">Log in</button>
  </form>
  <p><a href="/users/register">Need an account? Register</a></p>
  <p><a href="/users/reset_password">Forgot your password?</a></p>
</div>"""
end

end
|} pascal pascal

(** lib/<app>/controllers/auth/user_settings_controller.march *)
let user_settings_controller_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth

mod %s.Controllers.Auth.UserSettingsController do

alias %s.Accounts as Accounts
alias HttpServer as H

fn edit(conn) do
  match H.get_assign(conn, "current_user") do
  None ->
    conn |> H.redirect("/users/log_in") |> H.halt()
  Some(user) ->
    let email_gate = Accounts.User.update_email_gate(user, [])
    let pw_gate    = Accounts.change_user_password(user)
    H.html(conn, 200, render_settings(user, email_gate, pw_gate))
  end
end

fn update_email(conn) do
  match H.get_assign(conn, "current_user") do
  None ->
    conn |> H.redirect("/users/log_in") |> H.halt()
  Some(user) ->
    let params = H.body_params(conn)
    match Accounts.update_user_email(user, params) do
    Ok(_) ->
      conn
        |> H.put_flash("info", "Email updated successfully.")
        |> H.redirect("/users/settings")
    Err(gate) ->
      let pw_gate = Accounts.change_user_password(user)
      H.html(conn, 422, render_settings(user, gate, pw_gate))
    end
  end
end

fn update_password(conn) do
  match H.get_assign(conn, "current_user") do
  None ->
    conn |> H.redirect("/users/log_in") |> H.halt()
  Some(user) ->
    let params = H.body_params(conn)
    match Accounts.update_user_password(user, params) do
    Ok(_) ->
      conn
        |> H.put_flash("info", "Password updated. Please log in again.")
        |> H.redirect("/users/log_in")
    Err(gate) ->
      let email_gate = Accounts.User.update_email_gate(user, [])
      H.html(conn, 422, render_settings(user, email_gate, gate))
    end
  end
end

-- TODO: replace with your ~H template
pfn render_settings(user, _email_gate, _pw_gate) do
  ~H"""<div class="settings">
  <h1>Account settings for ${user.email}</h1>

  <section>
    <h2>Change email</h2>
    <form method="post" action="/users/settings/email">
      <label>New email <input type="email" name="email" required></label>
      <button type="submit">Update email</button>
    </form>
  </section>

  <section>
    <h2>Change password</h2>
    <form method="post" action="/users/settings/password">
      <label>New password <input type="password" name="password" required minlength="12"></label>
      <label>Confirm <input type="password" name="password_confirmation" required></label>
      <button type="submit">Update password</button>
    </form>
  </section>
</div>"""
end

end
|} pascal pascal

(** lib/<app>/controllers/auth/confirmation_controller.march *)
let confirmation_controller_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth

mod %s.Controllers.Auth.ConfirmationController do

alias %s.Accounts as Accounts
alias HttpServer as H

-- GET /users/confirm/:token — confirm the user's email address
fn confirm(conn) do
  let p = H.path_info(conn)
  let token = match p do
    Cons("users", Cons("confirm", Cons(t, Nil))) -> t
    _ -> ""
  end
  if token == "" do
    conn
      |> H.put_flash("error", "Confirmation link is invalid or has expired.")
      |> H.redirect("/")
      |> H.halt()
  else
    match Accounts.confirm_user(token) do
    Ok(_) ->
      conn
        |> H.put_flash("info", "Email confirmed successfully! You can now log in.")
        |> H.redirect("/users/log_in")
    Err(_) ->
      conn
        |> H.put_flash("error", "Confirmation link is invalid or has expired.")
        |> H.redirect("/")
    end
  end
end

-- POST /users/confirm — resend the confirmation email
fn resend(conn) do
  match H.get_assign(conn, "current_user") do
  None ->
    conn
      |> H.put_flash("error", "You must be logged in to resend confirmation.")
      |> H.redirect("/users/log_in")
  Some(user) ->
    Accounts.deliver_user_confirmation_instructions(
      user,
      fn token -> "/users/confirm/" ++ token
    )
    conn
      |> H.put_flash("info", "Confirmation email sent. Please check your inbox.")
      |> H.redirect("/")
  end
end

end
|} pascal pascal

(** test/support/accounts_fixtures.march *)
let accounts_fixtures_source pascal =
  Printf.sprintf {|-- Auto-generated by forge bastion gen auth
-- Test factory helpers for the Accounts context.
-- Use these in your test files to create users and tokens.

mod %s.AccountsFixtures do

alias %s.Accounts as Accounts

let user_counter = Vault.new()

pfn unique_email() do
  let n = match Vault.get(user_counter, "count") do
    Some(c) -> c + 1
    None -> 1
  end
  Vault.set(user_counter, "count", n)
  "user" ++ int_to_string(n) ++ "@example.com"
end

-- Valid user attributes (override any field).
fn user_fixture_attrs(overrides) do
  let defaults = [("email", unique_email()), ("password", "ValidPassword123!")]
  List.foldl(overrides, defaults, fn (k, v), acc ->
    List.keystore(acc, k, v)
  )
end

-- Create and persist a confirmed user.  Returns the user record.
fn user_fixture(overrides) do
  let attrs = user_fixture_attrs(overrides)
  match Accounts.register_user(attrs) do
  Ok(user) ->
    let token_str = Crypto.random_hex(32)
    let hashed = Crypto.sha256(token_str)
    -- Confirm directly via Depot (bypasses email flow in tests)
    let confirm_gate = Depot.Gate.cast_record(
      user,
      { confirmed_at = UtcDatetime.now() },
      ["confirmed_at"]
    )
    match Depot.Repo.update(%s.Accounts.User.schema(), confirm_gate) do
    Ok(confirmed) -> confirmed
    Err(_) -> user
    end
  Err(gate) ->
    -- Surface validation errors in test output for easier debugging
    let errs = Depot.Gate.errors(gate)
    let msg = List.map(errs, fn (f, m) -> f ++ ": " ++ m) |> List.join(", ")
    error("user_fixture failed: " ++ msg)
  end
end

-- Create a session token for `user`.  Returns the raw token string.
fn create_session_token(user) do
  match Accounts.create_session_token(user) do
  Ok(token) -> token
  Err(_) -> error("create_session_token failed")
  end
end

end
|} pascal pascal pascal

(* --------------------------------------------------------- run the generator *)

let run () =
  let app_snake = Filename.basename (Sys.getcwd ()) in
  let pascal = detect_app_name () in
  let ts  = int_of_float (Unix.time ()) in
  let ts2 = ts + 1 in

  let lib_dir       = Filename.concat "lib" app_snake in
  let accounts_dir  = Filename.concat lib_dir "accounts" in
  let auth_ctrl_dir = Filename.concat lib_dir "controllers/auth" in
  let mig_dir       = Filename.concat "priv" "depot/migrations" in
  let support_dir   = Filename.concat "test" "support" in

  mkdir_p accounts_dir;
  mkdir_p auth_ctrl_dir;
  mkdir_p mig_dir;
  mkdir_p support_dir;

  let f rel content =
    let path = rel in
    write_file path content;
    Printf.printf "* creating %s\n%!" path
  in

  f (Filename.concat accounts_dir  "user.march")
    (user_schema_source pascal);
  f (Filename.concat accounts_dir  "user_token.march")
    (user_token_schema_source pascal);
  f (Filename.concat accounts_dir  "user_notifier.march")
    (user_notifier_source pascal);
  f (Filename.concat lib_dir       "accounts.march")
    (accounts_context_source pascal);
  f (Filename.concat lib_dir       "auth.march")
    (auth_middleware_source pascal);
  f (Filename.concat auth_ctrl_dir "registration_controller.march")
    (registration_controller_source pascal);
  f (Filename.concat auth_ctrl_dir "session_controller.march")
    (session_controller_source pascal);
  f (Filename.concat auth_ctrl_dir "user_settings_controller.march")
    (user_settings_controller_source pascal);
  f (Filename.concat auth_ctrl_dir "confirmation_controller.march")
    (confirmation_controller_source pascal);
  f (Filename.concat mig_dir (Printf.sprintf "%d_create_users.march" ts))
    (users_migration_source ts);
  f (Filename.concat mig_dir (Printf.sprintf "%d_create_user_tokens.march" ts2))
    (user_tokens_migration_source ts2);
  f (Filename.concat support_dir   "accounts_fixtures.march")
    (accounts_fixtures_source pascal);

  Printf.printf {|
Done!  Files generated for %s.

Next steps
──────────

1. Add auth routes to your router  (lib/%s/router.march):

     -- Auth routes
     (:post, Cons("users", Cons("register", Nil)))    -> %s.Controllers.Auth.RegistrationController.create(conn)
     (:get,  Cons("users", Cons("register", Nil)))    -> %s.Controllers.Auth.RegistrationController.new(conn)
     (:post, Cons("users", Cons("log_in", Nil)))      -> %s.Controllers.Auth.SessionController.create(conn)
     (:get,  Cons("users", Cons("log_in", Nil)))      -> %s.Controllers.Auth.SessionController.new(conn)
     (:delete, Cons("users", Cons("log_out", Nil)))   -> %s.Controllers.Auth.SessionController.delete(conn)
     (:get,  Cons("users", Cons("settings", Nil)))    -> %s.Controllers.Auth.UserSettingsController.edit(conn)
     (:post, Cons("users", Cons("settings", Cons("email",    Nil)))) -> %s.Controllers.Auth.UserSettingsController.update_email(conn)
     (:post, Cons("users", Cons("settings", Cons("password", Nil)))) -> %s.Controllers.Auth.UserSettingsController.update_password(conn)
     (:get,  Cons("users", Cons("confirm", Cons(_, Nil))))  -> %s.Controllers.Auth.ConfirmationController.confirm(conn)
     (:post, Cons("users", Cons("confirm", Nil)))     -> %s.Controllers.Auth.ConfirmationController.resend(conn)

2. Plug the auth middleware into your router pipeline:

     alias %s.Auth as Auth

     -- Load current user on every request:
     let conn2 = Auth.load_current_user(conn)

3. Run the migrations:

     forge depot migrate

4. (Optional) Protect routes that require authentication:

     let conn3 = Auth.require_authenticated_user(conn2)

5. Replace the placeholder HTML in each controller with real ~H templates.

6. Implement %s.Accounts.UserNotifier to send real emails.
|} pascal app_snake
    pascal pascal pascal pascal pascal pascal pascal pascal
    pascal pascal pascal pascal;

  Ok ()
