(** forge.lock — read and write the dependency lockfile.

    Format (valid TOML subset):
    ────────────────────────────────────────────────────────────────────
    # This file is auto-generated by `forge deps`. Do not edit by hand.

    [manifest_hash]
    value = "sha256:abc123..."

    [lockfile]
    version = 2

    [[package]]
    name     = "json"
    version  = "1.4.7"
    source   = "registry:forge"
    hash     = "sha256:aabbccdd..."
    checksum = "sha256:99887766..."

    [[package]]
    name   = "depot"
    version = "0.2.1"
    source  = "git:https://github.com/user/depot.git"
    commit = "f7a3b1c9e4d2..."
    hash   = "sha256:11223344..."
    ────────────────────────────────────────────────────────────────────

    {2 The two hash fields, and why there are two}

    Before format 2, [hash] held values from two incompatible domains: for a
    registry dep it was the registry's published sha256 of the ORIGINAL
    `.tar.gz` bytes, and for a git dep it was the sha256 of the CANONICAL
    ARCHIVE of the extracted source tree.  Re-hashing a tree can never
    reproduce a tarball checksum, so no single integrity check could cover
    both — and the check `Resolver_cas_package` claims to perform was
    therefore unimplementable.  See
    `specs/2026-09-11-forge-offline-and-versioned-dep-cache-design.md` §0.3.

    Format 2 aligns them:

    - [hash] is ALWAYS the canonical-archive hash of the extracted tree
      (`Resolver_cas_package.hash_directory`), for every dep kind. This is the
      field an integrity check compares against, and it is checkable from what
      is on disk.
    - [checksum] is the SOURCE ARTIFACT's own published digest, present only
      where an upstream publishes one — today that is a registry dep's
      `.tar.gz` sha256. It is provenance: it says "this is the artifact the
      registry served", and it stays verifiable only if the tarball itself is
      cached (not yet — same design doc, §2.4).

    A format-1 lockfile is still READ (so an upgrade does not break a build),
    but its registry [hash] values are in the old domain and must not be
    verified against a tree. [read_format_version] is how a caller tells.

    The [manifest_hash] section holds the SHA-256 of forge.toml, used to
    detect drift.  If forge.toml changes without re-running `forge deps`,
    builds warn the user.

    Notes:
    - `version` is absent for branch and rev deps (no semver version).
    - `commit` is present for all git deps (tag/branch/rev).
    - `hash`   is the SHA-256 content hash of the canonical package archive of
               the extracted tree, for every dep kind (see above).
    - `checksum` is the upstream artifact digest, registry deps only.
*)

(** Lockfile format version this build writes. 1 = the pre-2026-09-12 format,
    whose registry `hash` values are tarball checksums rather than tree
    hashes; 2 = `hash` is uniformly a tree hash and `checksum` carries the
    registry digest. *)
let current_format_version = 2

(** A single resolved dependency entry. *)
type entry = {
  name    : string;
  version : string option;   (** semver version string; absent for branch/rev deps *)
  source  : string;          (** "registry:forge" | "git:<url>" | "path:<path>" *)
  commit  : string option;   (** git commit SHA; present for git deps *)
  hash    : string;
  (** SHA-256 of the canonical archive of the EXTRACTED TREE — one domain for
      every dep kind, so one integrity check covers all of them. *)
  checksum : string option;
  (** The upstream source artifact's own published digest (a registry
      `.tar.gz` sha256). Provenance, not a tree hash; [None] for git and path
      deps, which publish nothing. *)
}

(* ------------------------------------------------------------------ *)
(*  Hashing                                                            *)
(* ------------------------------------------------------------------ *)

(** Compute the manifest hash: SHA-256 of forge.toml content.
    Returns a string of the form "sha256:<hex-digest>". *)
let compute_manifest_hash content =
  let digest = Digestif.SHA256.digest_string content in
  "sha256:" ^ Digestif.SHA256.to_hex digest

(* ------------------------------------------------------------------ *)
(*  Writing                                                            *)
(* ------------------------------------------------------------------ *)

let write_string_opt oc key = function
  | None   -> ()
  | Some v ->
    output_string oc (Printf.sprintf "%s = %S\n" key v)

let write ?(toolchain=None) lock_path entries ~manifest_hash =
  (* Write to a temp file and rename into place: a write error (ENOSPC, …)
     never leaves a truncated/corrupt forge.lock, and the channel is always
     closed (Fun.protect). *)
  let tmp = lock_path ^ ".tmp" in
  let oc = open_out tmp in
  Fun.protect ~finally:(fun () -> close_out oc) (fun () ->
    output_string oc "# This file is auto-generated by `forge deps`. Do not edit by hand.\n";
    output_string oc "# Generated by Forge 0.1.0\n";
    output_char oc '\n';
    output_string oc "[lockfile]\n";
    output_string oc (Printf.sprintf "version = %d\n" current_format_version);
    output_char oc '\n';
    output_string oc "[manifest_hash]\n";
    output_string oc (Printf.sprintf "value = %S\n" manifest_hash);
    (* Record (do not pin) the toolchain that was active — for drift detection. *)
    (match toolchain with
     | Some v ->
       output_char oc '\n';
       output_string oc "[toolchain]\n";
       output_string oc (Printf.sprintf "version = %S\n" v)
     | None -> ());
    List.iter (fun e ->
        output_char oc '\n';
        output_string oc "[[package]]\n";
        output_string oc (Printf.sprintf "name   = %S\n" e.name);
        write_string_opt oc "version" e.version;
        output_string oc (Printf.sprintf "source = %S\n" e.source);
        write_string_opt oc "commit" e.commit;
        output_string oc (Printf.sprintf "hash   = %S\n" e.hash);
        write_string_opt oc "checksum" e.checksum
      ) entries);
  Sys.rename tmp lock_path

(* ------------------------------------------------------------------ *)
(*  Reading                                                            *)
(* ------------------------------------------------------------------ *)

(** Very simple parser for the forge.lock format.  We control the format,
    so we can make strong assumptions: no multi-line strings, no nested
    tables, [[package]] sections always use the same set of keys. *)

type parse_state =
  | Top
  | InManifest
  | InPackage of entry option  (** None = still accumulating fields *)

let unquote s =
  let s = String.trim s in
  let n = String.length s in
  if n >= 2 && s.[0] = '"' && s.[n - 1] = '"' then
    String.sub s 1 (n - 2)
  else s

let read lock_path =
  if not (Sys.file_exists lock_path) then
    Error (Printf.sprintf "forge.lock not found: %s" lock_path)
  else
  let ic = open_in lock_path in
  let text =
    Fun.protect ~finally:(fun () -> close_in_noerr ic) (fun () ->
      let n = in_channel_length ic in
      let buf = Bytes.create n in
      really_input ic buf 0 n;
      Bytes.to_string buf)
  in
  let lines = String.split_on_char '\n' text in
  let manifest_hash = ref None in
  let entries       = ref [] in
  let state         = ref Top in
  (* Mutable fields for the package being accumulated *)
  let cur_name    = ref "" in
  let cur_version = ref None in
  let cur_source  = ref "" in
  let cur_commit  = ref None in
  let cur_hash    = ref "" in
  let cur_checksum = ref None in
  let flush_package () =
    if !cur_name <> "" then begin
      let e = { name    = !cur_name;
                version = !cur_version;
                source  = !cur_source;
                commit  = !cur_commit;
                hash    = !cur_hash;
                checksum = !cur_checksum } in
      entries := e :: !entries;
      cur_name    := "";
      cur_version := None;
      cur_source  := "";
      cur_commit  := None;
      cur_hash    := "";
      cur_checksum := None
    end
  in
  let parse_kv line =
    match String.index_opt line '=' with
    | None    -> ()
    | Some eq ->
      let key = String.trim (String.sub line 0 eq) in
      let raw = String.trim (String.sub line (eq + 1) (String.length line - eq - 1)) in
      let value = unquote raw in
      (match !state with
       | InManifest ->
         if key = "value" then manifest_hash := Some value
       | InPackage _ ->
         (match key with
          | "name"    -> cur_name    := value
          | "version" -> cur_version := Some value
          | "source"  -> cur_source  := value
          | "commit"  -> cur_commit  := Some value
          | "hash"     -> cur_hash     := value
          | "checksum" -> cur_checksum := Some value
          | _          -> ())
       | Top -> ())
  in
  List.iter (fun raw ->
      let line = String.trim raw in
      if line = "" || (String.length line > 0 && line.[0] = '#') then
        ()
      else if line = "[[package]]" then begin
        flush_package ();
        state := InPackage None
      end else if line = "[manifest_hash]" then begin
        flush_package ();
        state := InManifest
      end else if String.length line >= 2 && line.[0] = '[' then begin
        flush_package ();
        state := Top
      end else
        parse_kv line
    ) lines;
  flush_package ();
  Ok (List.rev !entries, !manifest_hash)

(** Read one scalar key out of one `[section]` of [lock_path], without
    disturbing [read]'s 2-tuple signature.  Shared by [read_toolchain] and
    [read_format_version], which differ only in section and key. *)
let read_section_key lock_path ~section ~key =
  if not (Sys.file_exists lock_path) then None
  else begin
    let ic = open_in lock_path in
    let text =
      Fun.protect ~finally:(fun () -> close_in_noerr ic) (fun () ->
        let n = in_channel_length ic in
        let buf = Bytes.create n in
        really_input ic buf 0 n;
        Bytes.to_string buf)
    in
    let lines = String.split_on_char '\n' text in
    let inside = ref false and result = ref None in
    List.iter (fun raw ->
        let line = String.trim raw in
        if line = section then inside := true
        else if String.length line >= 2 && line.[0] = '[' then inside := false
        else if !inside then
          match String.index_opt line '=' with
          | Some eq ->
            let k = String.trim (String.sub line 0 eq) in
            if k = key then
              result := Some (unquote (String.sub line (eq + 1) (String.length line - eq - 1)))
          | None -> ()
      ) lines;
    !result
  end

(** The lockfile's declared format version. [None] means the `[lockfile]`
    section is absent, which is format 1 — written before 2026-09-12, when a
    registry dep's `hash` was its tarball checksum rather than a tree hash.
    Callers that verify a tree against `hash` must check this first. *)
let read_format_version lock_path =
  match read_section_key lock_path ~section:"[lockfile]" ~key:"version" with
  | None -> 1
  | Some v -> (try int_of_string (String.trim v) with _ -> 1)

(* Read just the recorded toolchain version from [lock_path], if any. Kept
   separate from [read] so its 2-tuple signature stays stable. *)
let read_toolchain lock_path =
  if not (Sys.file_exists lock_path) then None
  else begin
    let ic = open_in lock_path in
    let text =
      Fun.protect ~finally:(fun () -> close_in_noerr ic) (fun () ->
        let n = in_channel_length ic in
        let buf = Bytes.create n in
        really_input ic buf 0 n;
        Bytes.to_string buf)
    in
    let lines = String.split_on_char '\n' text in
    let in_tc = ref false and result = ref None in
    List.iter (fun raw ->
        let line = String.trim raw in
        if line = "[toolchain]" then in_tc := true
        else if String.length line >= 2 && line.[0] = '[' then in_tc := false
        else if !in_tc then
          match String.index_opt line '=' with
          | Some eq ->
            let key = String.trim (String.sub line 0 eq) in
            if key = "version" then
              result := Some (unquote (String.sub line (eq + 1) (String.length line - eq - 1)))
          | None -> ()
      ) lines;
    !result
  end

(* ------------------------------------------------------------------ *)
(*  Drift detection                                                    *)
(* ------------------------------------------------------------------ *)

(** Return true if the stored manifest hash in [lock_path] does not match
    the hash of [toml_content].  If the lock file cannot be read, returns
    true (treat as drifted). *)
let has_drifted lock_path toml_content =
  match read lock_path with
  | Error _ -> true
  | Ok (_, None) -> true
  | Ok (_, Some stored_hash) ->
    let current_hash = compute_manifest_hash toml_content in
    stored_hash <> current_hash
