(** forge.lock — read and write the dependency lockfile.

    Format (valid TOML subset):
    ────────────────────────────────────────────────────────────────────
    # This file is auto-generated by `forge deps`. Do not edit by hand.

    [manifest_hash]
    value = "sha256:abc123..."

    [[package]]
    name    = "json"
    version = "1.4.7"
    source  = "registry:forge"
    hash    = "blake3:aabbccdd..."

    [[package]]
    name   = "depot"
    version = "0.2.1"
    source  = "git:https://github.com/user/depot.git"
    commit = "f7a3b1c9e4d2..."
    hash   = "blake3:11223344..."
    ────────────────────────────────────────────────────────────────────

    The [manifest_hash] section holds the SHA-256 of forge.toml, used to
    detect drift.  If forge.toml changes without re-running `forge deps`,
    builds warn the user.

    Notes:
    - `version` is absent for branch and rev deps (no semver version).
    - `commit` is present for all git deps (tag/branch/rev).
    - `hash`   is the BLAKE3 content hash of the canonical package archive.
*)

(** A single resolved dependency entry. *)
type entry = {
  name    : string;
  version : string option;   (** semver version string; absent for branch/rev deps *)
  source  : string;          (** "registry:forge" | "git:<url>" | "path:<path>" *)
  commit  : string option;   (** git commit SHA; present for git deps *)
  hash    : string;          (** BLAKE3 content hash of the canonical archive *)
}

(* ------------------------------------------------------------------ *)
(*  Hashing                                                            *)
(* ------------------------------------------------------------------ *)

(** Compute the manifest hash: SHA-256 of forge.toml content.
    Returns a string of the form "sha256:<hex-digest>". *)
let compute_manifest_hash content =
  let digest = Digestif.SHA256.digest_string content in
  "sha256:" ^ Digestif.SHA256.to_hex digest

(* ------------------------------------------------------------------ *)
(*  Writing                                                            *)
(* ------------------------------------------------------------------ *)

let write_string_opt oc key = function
  | None   -> ()
  | Some v ->
    output_string oc (Printf.sprintf "%s = %S\n" key v)

let write lock_path entries ~manifest_hash =
  let oc = open_out lock_path in
  output_string oc "# This file is auto-generated by `forge deps`. Do not edit by hand.\n";
  output_string oc "# Generated by Forge 0.1.0\n";
  output_char oc '\n';
  output_string oc "[manifest_hash]\n";
  output_string oc (Printf.sprintf "value = %S\n" manifest_hash);
  List.iter (fun e ->
      output_char oc '\n';
      output_string oc "[[package]]\n";
      output_string oc (Printf.sprintf "name   = %S\n" e.name);
      write_string_opt oc "version" e.version;
      output_string oc (Printf.sprintf "source = %S\n" e.source);
      write_string_opt oc "commit" e.commit;
      output_string oc (Printf.sprintf "hash   = %S\n" e.hash)
    ) entries;
  close_out oc

(* ------------------------------------------------------------------ *)
(*  Reading                                                            *)
(* ------------------------------------------------------------------ *)

(** Very simple parser for the forge.lock format.  We control the format,
    so we can make strong assumptions: no multi-line strings, no nested
    tables, [[package]] sections always use the same set of keys. *)

type parse_state =
  | Top
  | InManifest
  | InPackage of entry option  (** None = still accumulating fields *)

let unquote s =
  let s = String.trim s in
  let n = String.length s in
  if n >= 2 && s.[0] = '"' && s.[n - 1] = '"' then
    String.sub s 1 (n - 2)
  else s

let read lock_path =
  if not (Sys.file_exists lock_path) then
    Error (Printf.sprintf "forge.lock not found: %s" lock_path)
  else
  let ic = open_in lock_path in
  let n  = in_channel_length ic in
  let buf = Bytes.create n in
  really_input ic buf 0 n;
  close_in ic;
  let text = Bytes.to_string buf in
  let lines = String.split_on_char '\n' text in
  let manifest_hash = ref None in
  let entries       = ref [] in
  let state         = ref Top in
  (* Mutable fields for the package being accumulated *)
  let cur_name    = ref "" in
  let cur_version = ref None in
  let cur_source  = ref "" in
  let cur_commit  = ref None in
  let cur_hash    = ref "" in
  let flush_package () =
    if !cur_name <> "" then begin
      let e = { name    = !cur_name;
                version = !cur_version;
                source  = !cur_source;
                commit  = !cur_commit;
                hash    = !cur_hash } in
      entries := e :: !entries;
      cur_name    := "";
      cur_version := None;
      cur_source  := "";
      cur_commit  := None;
      cur_hash    := ""
    end
  in
  let parse_kv line =
    match String.index_opt line '=' with
    | None    -> ()
    | Some eq ->
      let key = String.trim (String.sub line 0 eq) in
      let raw = String.trim (String.sub line (eq + 1) (String.length line - eq - 1)) in
      let value = unquote raw in
      (match !state with
       | InManifest ->
         if key = "value" then manifest_hash := Some value
       | InPackage _ ->
         (match key with
          | "name"    -> cur_name    := value
          | "version" -> cur_version := Some value
          | "source"  -> cur_source  := value
          | "commit"  -> cur_commit  := Some value
          | "hash"    -> cur_hash    := value
          | _         -> ())
       | Top -> ())
  in
  List.iter (fun raw ->
      let line = String.trim raw in
      if line = "" || (String.length line > 0 && line.[0] = '#') then
        ()
      else if line = "[[package]]" then begin
        flush_package ();
        state := InPackage None
      end else if line = "[manifest_hash]" then begin
        flush_package ();
        state := InManifest
      end else if String.length line >= 2 && line.[0] = '[' then begin
        flush_package ();
        state := Top
      end else
        parse_kv line
    ) lines;
  flush_package ();
  Ok (List.rev !entries, !manifest_hash)

(* ------------------------------------------------------------------ *)
(*  Drift detection                                                    *)
(* ------------------------------------------------------------------ *)

(** Return true if the stored manifest hash in [lock_path] does not match
    the hash of [toml_content].  If the lock file cannot be read, returns
    true (treat as drifted). *)
let has_drifted lock_path toml_content =
  match read lock_path with
  | Error _ -> true
  | Ok (_, None) -> true
  | Ok (_, Some stored_hash) ->
    let current_hash = compute_manifest_hash toml_content in
    stored_hash <> current_hash
