#!/usr/bin/env python3
# Generates bench/steady_state_ring.march with NB threaded histogram buckets.
NB = 18          # bucket count
SHIFT = 10       # bucket idx = clamp(floor(log2(ns)) - SHIFT, 0, NB-1)
                 # idx0 = ns < 2^(SHIFT+1)=2us ; idxK = [2^(SHIFT+K), 2^(SHIFT+K+1)) ns

cs = [f"c{k}" for k in range(NB)]          # bucket counter names
def csig(prefix): return ", ".join(prefix + c for c in cs)

# conditional-add for each bucket, given computed idx `b`
def incr_lines(indent):
    out = []
    for k in range(NB):
        out.append(f"{indent}let n{k} = {cs[k]} + (if b == {k} do 1 else 0 end)")
    return "\n".join(out)

recurse_args = ", ".join(f"n{k}" for k in range(NB))
pass_args    = ", ".join(cs)

src = f'''-- GENERATED by bench/gen_steady_state.py (NB={NB}, SHIFT={SHIFT}); edit the generator, not this file.
--
-- Steady-state, in-process request pipeline that substantiates March's two
-- headline runtime claims under sustained load:
--   (1) Flat RSS  -- precise reference counting reclaims per-op transients, so
--       memory tracks the live set, not the allocation rate. No GC heap grows.
--   (2) Bounded tail latency -- the preemptive M:N green-thread scheduler keeps
--       the request loop's p99.9 close to p50 even while CPU-bound siblings
--       oversubscribe every scheduler thread.
--
-- The per-op latency histogram is threaded as {NB} unboxed Int counters (no heap
-- store): stdlib RingBuf has no compiled backend, and Queue / NativeArray.set_int
-- retain memory under sustained churn in the compiled backend (see the spec).
-- See specs/2026-08-04-steady-state-tail-latency-demo.md.
mod SteadyStateRing do

  needs IO.Clock
  needs IO.Spawn

  -- ── Hot request-handling kernel (compiler-enforced zero allocation) ─────
  -- cap no_alloc statically rejects the four allocating AST shapes
  -- (non-empty tuple / record / constructor application / lambda).
  mod Hot do
    cap no_alloc

    -- One "request": `work` rounds of a MINSTD LCG step. Pure integer, no
    -- overflow (acc < 2^31, acc*48271 < 2^47 < 2^63), no allocation.
    fn process(seed : Int, work : Int) : Int do
      hot_go(seed, work)
    end

    fn hot_go(acc : Int, k : Int) : Int do
      if k <= 0 do acc
      else do
        let m = acc * 48271
        let acc2 = m - (m / 2147483647) * 2147483647
        hot_go(acc2, k - 1)
      end
      end
    end

    -- Histogram bucket: clamp(floor(log2(ns)) - {SHIFT}, 0, {NB-1}).
    fn bucket_of(ns : Int) : Int do
      let raw = log2_floor(ns, 0)
      let shifted = raw - {SHIFT}
      if shifted < 0 do 0
      else if shifted > {NB-1} do {NB-1}
      else shifted end
      end
    end

    fn log2_floor(ns : Int, k : Int) : Int do
      if ns <= 1 do k
      else log2_floor(ns / 2, k + 1) end
    end
  end

  -- ── CPU-bound sibling green threads (the scheduler stressor) ────────────
  pfn spin(n : Int) : Int do
    if n < 2 do n
    else spin(n - 1) + spin(n - 2) end
  end

  pfn sib_loop(rounds : Int, work : Int, acc : Int) : Int do
    if rounds <= 0 do acc
    else sib_loop(rounds - 1, work, acc + spin(work)) end
  end

  pfn spawn_siblings(k : Int, work : Int) : Unit do
    if k <= 0 do ()
    else do
      let _t = task_spawn(fn x -> sib_loop(1000000000, work, 0))
      spawn_siblings(k - 1, work)
    end
    end
  end

  -- ── Steady-state loop ───────────────────────────────────────────────────
  -- Each op times one request (process the request through the kernel) and
  -- folds its latency into the threaded histogram. unix_time() allocates
  -- transient boxed Floats every iteration; RC frees them immediately, which
  -- is exactly claim (1): a high per-op allocation rate with a flat live set.
  pfn drive(i : Int, n : Int, work : Int, mn : Int, mx : Int, sum : Int,
            {csig("")}) : Unit do
    if i >= n do
      report(n, work, mn, mx, sum, {pass_args})
    else do
      let seed = (i - (i / 2147483646) * 2147483646) + 1
      let t0 = unix_time(())
      let r = Hot.process(seed, work)
      let t1 = unix_time(())
      let raw = float_to_int((t1 -. t0) *. 1000000000.0)
      let ns = if raw < 0 do 0 else raw end
      let b = Hot.bucket_of(ns)
      let mn2 = if ns < mn do ns else mn end
      let mx2 = if ns > mx do ns else mx end
{incr_lines("      ")}
      drive(i + 1, n, work, mn2, mx2, sum + r, {recurse_args})
    end
    end
  end

  pfn report(n : Int, work : Int, mn : Int, mx : Int, sum : Int,
             {csig("")}) : Unit do
    println("# steady_state_ring")
    println("OPS " ++ int_to_string(n))
    println("WORK " ++ int_to_string(work))
    println("SHIFT {SHIFT}")
    println("NB {NB}")
    println("MIN_NS " ++ int_to_string(mn))
    println("MAX_NS " ++ int_to_string(mx))
    println("CHECKSUM " ++ int_to_string(sum))
{chr(10).join(f'    println("BUCKET {k} " ++ int_to_string({cs[k]}))' for k in range(NB))}
    println("END")
    System.exit(0)
  end

  pfn env_int(name : String, dflt : Int) : Int do
    match System.env(name) do
      Some(s) -> match String.to_int(s) do
        Ok(v) -> v
        Err(_) -> dflt
      end
      None -> dflt
    end
  end

  pfn main() : Unit do
    let n = env_int("STEADY_OPS", 2000000)
    let work = env_int("STEADY_WORK", 512)
    let siblings = env_int("STEADY_SIBLINGS", 0)
    let sibwork = env_int("STEADY_SIBWORK", 28)
    spawn_siblings(siblings, sibwork)
    drive(0, n, work, 1000000000, 0, 0, {", ".join("0" for _ in range(NB))})
  end

end
'''
import sys
sys.stdout.write(src)
