id = "march"
name = "March"
version = "0.0.1"
schema_version = 1
authors = ["March Contributors"]
description = "March language support for Zed"

[grammars.march]
repository = "file:///Users/80197052/code/march/tree-sitter-march"
rev = "406f8b08de99b4e180e1023a4d411d58161e6df3"

[language_servers.march-lsp]
name = "March LSP"
languages = ["March"]
