id = "march"
name = "March"
version = "0.0.1"
schema_version = 1
authors = ["March Contributors"]
description = "March language support for Zed"

[grammars.march]
repository = "file:///Users/80197052/code/march"
rev = "ad60a650de3abdae96bd479f6d09791a2affcd45"
path = "tree-sitter-march"

[language_servers.march-lsp]
name = "March LSP"
languages = ["March"]
