(executable
 (name discover_compress)
 (modules discover_compress)
 (libraries dune-configurator))

(rule
 (targets compress_cflags.sexp compress_libs.sexp)
 (action (run ./discover_compress.exe)))

(library
 (name march_eval)
 (modules (:standard \ discover_compress))
 (libraries march_ast march_modules march_scheduler march_coverage march_doctest unix digestif)
 (foreign_stubs
  (language c)
  (names compress_stubs)
  (flags (:standard (:include compress_cflags.sexp))))
 (c_library_flags (:include compress_libs.sexp)))
