#!/usr/bin/env python3
"""gen-lang-docs.py: render the language-reference chapters from specs/lang/ into docs/.

specs/lang/ is the CANONICAL language reference. docs/ is the Jekyll root that
march-lang.org serves (GitHub's legacy Jekyll over docs/ on main; see the header of
scripts/gen-stdlib-docs.sh), so every chapter the site publishes is a generated,
committed copy of its specs/lang/ source. Edit the specs/lang/ file, then run this
script; never hand-edit a generated docs/ page (its first line after the front matter
says so, and scripts/check-docs.sh Check F fails the build if it drifts).

What the rendering changes, and why:
  * The "> Part of the March Language Reference; see [specs/lang/index.md](...)" banner
    is dropped: it orients a reader browsing specs/ on GitHub, not a site reader.
  * A GENERATED marker comment is inserted right after the front matter.
  * Relative Markdown links are re-resolved. A link is written relative to
    specs/lang/ in the source; the rendered copy lives in docs/, so each target is
    resolved to a repo path and re-expressed:
      - another generated chapter         -> its docs/ file name (e.g. `types.md`)
      - a file under docs/                -> relative to docs/ (e.g. `tour.md`)
      - anything else in the repo         -> a github.com blob/tree URL
    A relative link whose target does not exist is a hard error, so a dead link in a
    chapter is caught here rather than on the live site.
  Absolute links, `{{ site.baseurl }}` links, and in-page `#anchors` pass through.
  Nothing inside fenced code blocks or inline code spans is touched.

Usage:
  scripts/gen-lang-docs.py            regenerate docs/<chapter>.md for every chapter
  scripts/gen-lang-docs.py --check    exit 1 (naming each file) if any committed page
                                      differs from what this script would write
"""

import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC_DIR = "specs/lang"
OUT_DIR = "docs"
REPO_URL = "https://github.com/march-language/march"

# specs/lang/<source> -> docs/<output>. Every specs/lang/*.md that carries Jekyll front
# matter is a published chapter and must appear here (enforced below), so a new chapter
# cannot silently go unpublished. type-system.md renders to types.md because that docs/
# file name predates the canonical reference and other pages link to it.
# specs/lang/index.md is deliberately NOT generated: docs/index.md is the site's landing
# page, a different document from the spec's umbrella index.
CHAPTERS = {
    "actors.md": "actors.md",
    "capabilities.md": "capabilities.md",
    "capability-enforcement.md": "capability-enforcement.md",
    "choreography.md": "choreography.md",
    "clustering.md": "clustering.md",
    "interfaces.md": "interfaces.md",
    "linear-types.md": "linear-types.md",
    "memory-model.md": "memory-model.md",
    "modules.md": "modules.md",
    "parallelism.md": "parallelism.md",
    "pattern-matching.md": "pattern-matching.md",
    "refinement-types.md": "refinement-types.md",
    "safety-by-construction.md": "safety-by-construction.md",
    "session-types.md": "session-types.md",
    "supervision.md": "supervision.md",
    "type-system.md": "types.md",
}

MARKER = "<!-- GENERATED from {src} by scripts/gen-lang-docs.py. Do not edit this file: edit {src} and run scripts/gen-lang-docs.py. -->"
MARKER_PREFIX = "<!-- GENERATED from specs/lang/"

BANNER_RE = re.compile(r"^> Part of the March Language Reference[;:,]? see \[specs/lang/index\.md\]\([^)]*\)\.?\s*$")
FENCE_RE = re.compile(r"^\s*(```|~~~)")
# An inline link or image target: `](target)` or `](target "title")`.
LINK_RE = re.compile(r"\]\(([^()\s]+)((?:\s+\"[^\"]*\")?)\)")
CODE_SPAN_RE = re.compile(r"(`+)(.+?)\1")


class GenError(Exception):
    pass


def is_passthrough(target):
    return (
        target.startswith("#")
        or target.startswith("/")
        or target.startswith("{{")
        or re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target) is not None  # http:, mailto:, …
    )


def rewrite_target(target, src_rel):
    if is_passthrough(target):
        return target
    path, sep, anchor = target.partition("#")
    anchor = sep + anchor
    resolved = os.path.normpath(os.path.join(os.path.dirname(src_rel), path))
    abs_path = os.path.join(ROOT, resolved)
    if resolved.startswith("..") or not os.path.exists(abs_path):
        raise GenError(f"{src_rel}: link target '{target}' resolves to '{resolved}', which does not exist")
    src_dir_prefix = SRC_DIR + "/"
    if resolved.startswith(src_dir_prefix) and resolved[len(src_dir_prefix):] in CHAPTERS:
        return CHAPTERS[resolved[len(src_dir_prefix):]] + anchor
    if resolved == OUT_DIR or resolved.startswith(OUT_DIR + "/"):
        rel = os.path.relpath(resolved, OUT_DIR)
        return (rel if rel != "." else "./") + anchor
    kind = "tree" if os.path.isdir(abs_path) else "blob"
    return f"{REPO_URL}/{kind}/main/{resolved}{anchor}"


def rewrite_links_in_line(line, src_rel):
    # Split out inline code spans so a `](x)` inside backticks is left alone.
    out, pos = [], 0
    for m in CODE_SPAN_RE.finditer(line):
        out.append(LINK_RE.sub(lambda l: "](" + rewrite_target(l.group(1), src_rel) + l.group(2) + ")", line[pos:m.start()]))
        out.append(m.group(0))
        pos = m.end()
    out.append(LINK_RE.sub(lambda l: "](" + rewrite_target(l.group(1), src_rel) + l.group(2) + ")", line[pos:]))
    return "".join(out)


def render(src_name):
    src_rel = f"{SRC_DIR}/{src_name}"
    with open(os.path.join(ROOT, src_rel), encoding="utf-8") as f:
        lines = f.read().split("\n")
    if not lines or lines[0] != "---":
        raise GenError(f"{src_rel}: a published chapter must start with Jekyll front matter")
    try:
        fm_end = lines.index("---", 1)
    except ValueError:
        raise GenError(f"{src_rel}: unterminated front matter")
    front, body = lines[: fm_end + 1], lines[fm_end + 1 :]

    # Drop the specs-only banner (and one blank line on either side of it).
    for i, line in enumerate(body):
        if BANNER_RE.match(line):
            j = i + 1 if i + 1 < len(body) and body[i + 1].strip() == "" else i
            del body[i : j + 1]
            break

    out, in_fence, fence = [], False, None
    for line in body:
        m = FENCE_RE.match(line)
        if m:
            if not in_fence:
                in_fence, fence = True, m.group(1)
            elif m.group(1) == fence:
                in_fence = False
            out.append(line)
            continue
        out.append(line if in_fence else rewrite_links_in_line(line, src_rel))

    while out and out[0].strip() == "":
        out.pop(0)
    return "\n".join(front + ["", MARKER.format(src=src_rel), ""] + out)


def main(argv):
    check = "--check" in argv[1:]
    errors, stale = [], []

    published = sorted(
        n for n in os.listdir(os.path.join(ROOT, SRC_DIR))
        if n.endswith(".md") and open(os.path.join(ROOT, SRC_DIR, n), encoding="utf-8").readline().rstrip("\n") == "---"
    )
    for n in published:
        if n not in CHAPTERS:
            errors.append(f"{SRC_DIR}/{n} has Jekyll front matter but is not in CHAPTERS in scripts/gen-lang-docs.py; add it (or drop its front matter)")
    for n in CHAPTERS:
        if n not in published:
            errors.append(f"CHAPTERS lists {SRC_DIR}/{n}, which does not exist or has no front matter")

    # A docs/ page carrying the marker whose source is no longer a chapter is an orphan.
    outputs = set(CHAPTERS.values())
    for n in sorted(os.listdir(os.path.join(ROOT, OUT_DIR))):
        p = os.path.join(ROOT, OUT_DIR, n)
        if n.endswith(".md") and n not in outputs and os.path.isfile(p):
            with open(p, encoding="utf-8") as f:
                if MARKER_PREFIX in f.read():
                    errors.append(f"{OUT_DIR}/{n} is marked GENERATED but no chapter in CHAPTERS produces it; delete it or restore its source")

    for src_name, out_name in CHAPTERS.items():
        if src_name not in published:
            continue
        try:
            rendered = render(src_name)
        except GenError as e:
            errors.append(str(e))
            continue
        out_rel = f"{OUT_DIR}/{out_name}"
        out_abs = os.path.join(ROOT, out_rel)
        current = open(out_abs, encoding="utf-8").read() if os.path.exists(out_abs) else None
        if current == rendered:
            continue
        if check:
            stale.append((out_rel, f"{SRC_DIR}/{src_name}"))
        else:
            with open(out_abs, "w", encoding="utf-8") as f:
                f.write(rendered)
            print(f"  wrote {out_rel}  (from {SRC_DIR}/{src_name})")

    for e in errors:
        print(f"  ERROR: {e}")
    for out_rel, src_rel in stale:
        print(f"  STALE: {out_rel} differs from what {src_rel} renders to")
    if stale:
        print("  docs/ language chapters are generated. Edit the specs/lang/ source, then run:")
        print("      scripts/gen-lang-docs.py")
        print("  and commit the regenerated docs/ page(s) together with the source.")
    if errors or stale:
        return 1
    if check:
        print(f"  ok — {len(CHAPTERS)} generated chapters match their specs/lang/ sources")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
