module C = Configurator.V1

let () =
  C.main ~name:"blake3" (fun c ->
    let is_macos = C.ocaml_config_var c "system" = Some "macosx" in
    let macos_prefix () =
      if Sys.file_exists "/opt/homebrew/include/blake3.h" then "/opt/homebrew"
      else "/usr/local"
    in
    (* On macOS, prefer a static libblake3.a when one is present so the binary
       carries no blake3 dylib dependency (runs on machines without Homebrew).
       Falls back to dynamic -lblake3 otherwise (typical local dev). *)
    let static_macos =
      if is_macos then
        let prefix = macos_prefix () in
        let archive = prefix ^ "/lib/libblake3.a" in
        if Sys.file_exists archive then
          Some { C.Pkg_config.cflags = [ "-I" ^ prefix ^ "/include" ]; libs = [ archive ] }
        else None
      else None
    in
    let default =
      if is_macos then
        let prefix = macos_prefix () in
        { C.Pkg_config.cflags = [ "-I" ^ prefix ^ "/include" ]
        ; libs = [ "-L" ^ prefix ^ "/lib"; "-lblake3" ]
        }
      else { C.Pkg_config.cflags = []; libs = [ "-lblake3" ] }
    in
    let conf =
      match static_macos with
      | Some s -> s            (* static archive takes precedence on macOS *)
      | None ->
        (match C.Pkg_config.get c with
         | None -> default
         | Some pc ->
           (match C.Pkg_config.query pc ~package:"blake3" with
            | None -> default
            | Some deps -> deps))
    in
    C.Flags.write_sexp "blake3_cflags.sexp" conf.cflags;
    C.Flags.write_sexp "blake3_libs.sexp" conf.libs;
    (* Also emit an OCaml module so non-configurator consumers (bin/main.ml,
       which shells out to clang directly to link runtime/march_blake3.c
       into the reload server) use the SAME discovered flags instead of a
       hand-rolled probe that can silently diverge (e.g. missing the
       pkg-config tier, or a different macOS-detection heuristic). This is
       the single source of truth for "how do we find libblake3". *)
    let ml_list_literal l =
      "[" ^ String.concat "; " (List.map (Printf.sprintf "%S") l) ^ "]"
    in
    let oc = open_out "blake3_flags.ml" in
    Printf.fprintf oc
      "(* Generated by lib/cas/discover.ml — do not edit by hand. *)\n\
       let cflags : string list = %s\n\
       let libs : string list = %s\n"
      (ml_list_literal conf.cflags) (ml_list_literal conf.libs);
    close_out oc)
